"""Add new trending/popular products to flowpicker.db across all layers.

Each entry: (option_id, name, attrs_dict)
Position auto-assigned starting after each layer's max position.
"""

import sqlite3
import os

DB = os.path.join(os.path.dirname(__file__), '..', 'data', 'flowpicker.db')

# ============================================================================
# IDE LAYER — new entries
# ============================================================================
IDE_NEW = [
    ('trae', 'Trae', {
        'notes': 'ByteDance AI-native IDE with SOLO mode for autonomous coding',
        'os': 'macOS, Windows, Linux',
        'pricing': 'Free (premium tiers)',
        'aiIntegration': 'AI-native',
        'interface': 'GUI',
        'openSource': 'No',
        'setup': 'Zero',
        'bestFor': 'AI-first coding with SOLO autonomous mode, free Claude/GPT access at launch',
        'capabilities': 'AI Chat, Builder mode, SOLO autonomous mode, Multi-file edits, Plugins, VS Code import, MCP, Custom Agents',
        'languages': 'All major, via LSP',
        'extensibility': 'Extensions',
        'collaboration': 'Via Git',
        'released': '2024',
        'websiteUrl': 'https://trae.ai/',
        'docsUrl': 'https://docs.trae.ai/',
    }),
    ('antigravity', 'Google Antigravity', {
        'notes': 'Google agent-first IDE built on Gemini 3 with autonomous workspace',
        'os': 'macOS, Windows, Linux',
        'pricing': 'Free preview',
        'aiIntegration': 'AI-native',
        'interface': 'GUI',
        'openSource': 'No',
        'setup': 'Zero',
        'bestFor': 'Agent-first development where Gemini 3 Pro drives end-to-end tasks across editor, terminal, and browser',
        'capabilities': 'Manager surface, Agent workspace, Browser control, Terminal control, Multi-agent orchestration, Gemini 3 Pro/Claude/GPT support, Artifacts (task lists, screenshots, walkthroughs)',
        'languages': 'All major, via LSP',
        'extensibility': 'Extensions (VS Code compatible)',
        'collaboration': 'Via Git',
        'released': '2025',
        'websiteUrl': 'https://antigravity.google/',
        'docsUrl': 'https://antigravity.google/docs',
    }),
    ('kiro', 'Kiro', {
        'notes': 'AWS spec-driven AI IDE focused on production-grade code generation',
        'os': 'macOS, Windows, Linux',
        'pricing': 'Freemium',
        'aiIntegration': 'AI-native',
        'interface': 'GUI',
        'openSource': 'No',
        'setup': 'Zero',
        'bestFor': 'Spec-driven development with structured requirements, design docs, and tasks before code generation',
        'capabilities': 'Spec mode, Vibe mode, Steering files, Hooks, MCP, Agent Hooks, VS Code import',
        'languages': 'All major, via LSP',
        'extensibility': 'Extensions (VS Code compatible)',
        'collaboration': 'Via Git',
        'released': '2025',
        'websiteUrl': 'https://kiro.dev/',
        'docsUrl': 'https://kiro.dev/docs/',
    }),
    ('void', 'Void Editor', {
        'notes': 'Open-source Cursor alternative; fully transparent and self-hostable',
        'os': 'macOS, Windows, Linux',
        'pricing': 'Free',
        'aiIntegration': 'AI-native',
        'interface': 'GUI',
        'openSource': 'Yes',
        'setup': 'Zero',
        'bestFor': 'Privacy-conscious developers who want Cursor-style features with full code transparency and BYO model',
        'capabilities': 'AI inline edits, Chat, Multi-file edits, Agent mode, Tab autocomplete, BYO model, Local model support, Extensions',
        'languages': 'All major, via LSP',
        'extensibility': 'Extensions (VS Code compatible)',
        'collaboration': 'Via Git',
        'released': '2024',
        'websiteUrl': 'https://voideditor.com/',
        'docsUrl': 'https://voideditor.com/docs',
    }),
    ('pearai', 'PearAI', {
        'notes': 'Open-source fork of VS Code with built-in AI features',
        'os': 'macOS, Windows, Linux',
        'pricing': 'Freemium',
        'aiIntegration': 'AI-native',
        'interface': 'GUI',
        'openSource': 'Yes',
        'setup': 'Zero',
        'bestFor': 'OSS Cursor alternative bundling Continue-style chat, Aider terminal, and Roo Code agent under one roof',
        'capabilities': 'AI Chat, Tab autocomplete, Multi-file edits, Bundled Aider, Roo Code agent, MCP, BYO model',
        'languages': 'All major, via LSP',
        'extensibility': 'Extensions (VS Code compatible)',
        'collaboration': 'Via Git',
        'released': '2024',
        'websiteUrl': 'https://trypear.ai/',
        'docsUrl': 'https://trypear.ai/docs',
    }),
    ('lapce', 'Lapce', {
        'notes': 'Rust-based lightning-fast modal-friendly code editor',
        'os': 'macOS, Windows, Linux',
        'pricing': 'Free',
        'aiIntegration': 'AI via extension',
        'interface': 'GUI',
        'openSource': 'Yes',
        'setup': 'Zero',
        'bestFor': 'Native Rust performance with built-in LSP, remote dev, and modal editing',
        'capabilities': 'Vim mode, Multi-cursor, GPU rendering, Built-in LSP, Built-in remote dev, WASI plugins',
        'languages': 'All major, via LSP',
        'extensibility': 'Plugins',
        'collaboration': 'Via Git',
        'released': '2021',
        'websiteUrl': 'https://lapce.dev/',
        'docsUrl': 'https://docs.lapce.dev/',
    }),
    ('positron', 'Positron', {
        'notes': 'Posit (RStudio) next-gen data science IDE built on VS Code',
        'os': 'macOS, Windows, Linux',
        'pricing': 'Free',
        'aiIntegration': 'AI via extension',
        'interface': 'GUI',
        'openSource': 'Yes',
        'setup': 'Zero',
        'bestFor': 'Polyglot data science workflows with first-class R and Python support and notebook UX',
        'capabilities': 'Data viewer, Variables pane, R + Python sessions, Quarto, Plot pane, Extensions, Jupyter notebooks',
        'languages': 'R, Python, SQL, others via LSP',
        'extensibility': 'Extensions (VS Code compatible)',
        'collaboration': 'Via Git',
        'released': '2024',
        'websiteUrl': 'https://positron.posit.co/',
        'docsUrl': 'https://positron.posit.co/start.html',
    }),
    ('rstudio', 'RStudio', {
        'notes': 'Industry-standard IDE for R statistical computing and data science',
        'os': 'macOS, Windows, Linux, Server',
        'pricing': 'Freemium',
        'aiIntegration': 'AI via extension',
        'interface': 'GUI',
        'openSource': 'Yes',
        'setup': 'Low',
        'bestFor': 'R programming, data science workflows, statistics, and Quarto/RMarkdown authoring',
        'capabilities': 'R sessions, Quarto, RMarkdown, Plot pane, Project mode, Knitr, Shiny preview',
        'languages': 'R, Python, SQL',
        'extensibility': 'Plugins',
        'collaboration': 'Via Git',
        'released': '2011',
        'websiteUrl': 'https://posit.co/products/open-source/rstudio/',
        'docsUrl': 'https://docs.posit.co/ide/user/',
    }),
    ('spyder', 'Spyder', {
        'notes': 'Scientific Python IDE with variable explorer and IPython console',
        'os': 'macOS, Windows, Linux',
        'pricing': 'Free',
        'aiIntegration': 'AI via extension',
        'interface': 'GUI',
        'openSource': 'Yes',
        'setup': 'Low',
        'bestFor': 'Python data science, scientific computing, and exploratory analysis with MATLAB-like UX',
        'capabilities': 'Variable explorer, IPython console, Profiler, Debugger, Plots pane, Help pane',
        'languages': 'Python',
        'extensibility': 'Plugins',
        'collaboration': 'Via Git',
        'released': '2009',
        'websiteUrl': 'https://www.spyder-ide.org/',
        'docsUrl': 'https://docs.spyder-ide.org/',
    }),
    ('cursor-mobile', 'Cursor Mobile', {
        'notes': 'Mobile-first companion to Cursor for reviewing & directing background agents',
        'os': 'iOS, Android',
        'pricing': 'Freemium',
        'aiIntegration': 'AI-native',
        'interface': 'GUI',
        'openSource': 'No',
        'setup': 'Zero',
        'bestFor': 'Driving background agents, reviewing PRs and diffs, and dispatching work from a phone',
        'capabilities': 'Background agents, Code review, Diff viewer, Chat, Push notifications, Voice prompts',
        'languages': 'All major',
        'extensibility': 'Not applicable',
        'collaboration': 'Via Git',
        'released': '2025',
        'websiteUrl': 'https://cursor.com/mobile',
        'docsUrl': 'https://docs.cursor.com/mobile',
    }),
    ('eclipse', 'Eclipse', {
        'notes': 'Long-standing enterprise Java/JVM IDE with massive plugin ecosystem',
        'os': 'macOS, Windows, Linux',
        'pricing': 'Free',
        'aiIntegration': 'AI via extension',
        'interface': 'GUI',
        'openSource': 'Yes',
        'setup': 'Medium',
        'bestFor': 'Java/JVM enterprise development, plugin-driven custom IDEs, embedded toolchains',
        'capabilities': 'Java tooling, Plugin ecosystem, JDT, PDE, Modeling, Refactoring, Debugger',
        'languages': 'Java, C/C++, Python, PHP, more via plugins',
        'extensibility': 'Plugins',
        'collaboration': 'Via Git',
        'released': '2001',
        'websiteUrl': 'https://www.eclipse.org/ide/',
        'docsUrl': 'https://help.eclipse.org/',
    }),
    ('netbeans', 'Apache NetBeans', {
        'notes': 'Free open-source IDE for Java, JS, PHP, and HTML5',
        'os': 'macOS, Windows, Linux',
        'pricing': 'Free',
        'aiIntegration': 'AI via extension',
        'interface': 'GUI',
        'openSource': 'Yes',
        'setup': 'Medium',
        'bestFor': 'Java SE/EE projects, Maven/Gradle workflows, and standards-based plugin development',
        'capabilities': 'Java tooling, Maven, Gradle, Profiler, Debugger, Refactoring, Web frameworks',
        'languages': 'Java, JavaScript, PHP, HTML',
        'extensibility': 'Plugins',
        'collaboration': 'Via Git',
        'released': '1996',
        'websiteUrl': 'https://netbeans.apache.org/',
        'docsUrl': 'https://netbeans.apache.org/front/main/help/',
    }),
]

# ============================================================================
# LLM LAYER — new entries (hot/trending late-2025/early-2026)
# ============================================================================
LLM_NEW = [
    ('gemini-3-pro', 'Gemini 3 Pro', {
        'provider': 'Google',
        'hosting': 'Closed/API',
        'modelId': 'gemini-3-pro',
        'priceTier': 'Premium',
        'priceInput': '$2',
        'priceOutput': '$12',
        'priceCache': '$0.50',
        'contextWindow': '1M+',
        'contextTier': '500K+',
        'maxOutput': '64K',
        'modality': 'Multimodal (vision, audio, video)',
        'capabilities': 'Vision, Audio, Video, Tool use, Deep Think, Generative UI, Streaming, Function calling, Prompt caching, Code execution',
        'speedTier': 'Medium',
        'latency': 'medium',
        'benchmark': 'Top across LMArena and reasoning suites',
        'sweBench': '76%',
        'humanEval': '95%',
        'mmlu': '92%',
        'bestFor': 'Long-horizon agentic tasks, generative UI, multi-modal reasoning, Antigravity-driven workflows',
        'knowledgeCutoff': 'Jan 2026',
        'released': 'Nov 2025',
        'websiteUrl': 'https://deepmind.google/models/gemini/pro/',
        'docsUrl': 'https://ai.google.dev/gemini-api/docs/models',
    }),
    ('gemini-3-deep-think', 'Gemini 3 Deep Think', {
        'provider': 'Google',
        'hosting': 'Closed/API',
        'modelId': 'gemini-3-pro-deep-think',
        'priceTier': 'Premium',
        'priceInput': '$5',
        'priceOutput': '$30',
        'priceCache': '$1',
        'contextWindow': '1M+',
        'contextTier': '500K+',
        'maxOutput': '64K',
        'modality': 'Multimodal (vision)',
        'capabilities': 'Vision, Tool use, Extended reasoning, Multi-step planning, Function calling',
        'speedTier': 'Slow/Reasoning',
        'latency': 'high',
        'benchmark': 'Top on FrontierMath, Humanity Last Exam, ARC-AGI-2',
        'sweBench': '80%',
        'humanEval': '96%',
        'mmlu': '93%',
        'bestFor': 'Hardest reasoning, research analysis, math olympiad and competitive programming',
        'knowledgeCutoff': 'Jan 2026',
        'released': 'Dec 2025',
        'websiteUrl': 'https://deepmind.google/models/gemini/',
        'docsUrl': 'https://ai.google.dev/gemini-api/docs/models',
    }),
    ('gpt-5-1', 'GPT-5.1', {
        'provider': 'OpenAI',
        'hosting': 'Closed/API',
        'modelId': 'gpt-5.1',
        'priceTier': 'Mid',
        'priceInput': '$1.25',
        'priceOutput': '$10',
        'priceCache': '$0.125',
        'contextWindow': '400K',
        'contextTier': '128K-500K',
        'maxOutput': '128K',
        'modality': 'Multimodal (vision)',
        'capabilities': 'Vision, Tool use, Adaptive reasoning, Streaming, Structured output, Function calling, Prompt caching, Personality presets',
        'speedTier': 'Medium',
        'latency': 'medium',
        'benchmark': 'Strong on AIME, SWE-bench, Tau-Bench',
        'sweBench': '76%',
        'humanEval': '95%',
        'mmlu': '89%',
        'bestFor': 'Default daily-driver coding agent with adaptive reasoning and warmer chat tone',
        'knowledgeCutoff': 'Oct 2025',
        'released': 'Nov 2025',
        'websiteUrl': 'https://openai.com/gpt-5/',
        'docsUrl': 'https://platform.openai.com/docs/models',
    }),
    ('gpt-5-1-codex', 'GPT-5.1 Codex', {
        'provider': 'OpenAI',
        'hosting': 'Closed/API',
        'modelId': 'gpt-5.1-codex',
        'priceTier': 'Mid',
        'priceInput': '$1.25',
        'priceOutput': '$10',
        'priceCache': '$0.125',
        'contextWindow': '400K',
        'contextTier': '128K-500K',
        'maxOutput': '128K',
        'modality': 'Text + Vision',
        'capabilities': 'Tool use, Coding-specialized fine-tune, Long-running tasks, Streaming, Function calling, Prompt caching',
        'speedTier': 'Medium',
        'latency': 'medium',
        'benchmark': 'SWE-bench Verified ~75%',
        'sweBench': '75%',
        'humanEval': '95%',
        'mmlu': '88%',
        'bestFor': 'Codex CLI and long-horizon coding agents; engineered for terminal-driven workflows',
        'knowledgeCutoff': 'Oct 2025',
        'released': 'Nov 2025',
        'websiteUrl': 'https://openai.com/index/introducing-codex/',
        'docsUrl': 'https://platform.openai.com/docs/models/gpt-5.1-codex',
    }),
    ('gpt-5-1-codex-max', 'GPT-5.1 Codex Max', {
        'provider': 'OpenAI',
        'hosting': 'Closed/API',
        'modelId': 'gpt-5.1-codex-max',
        'priceTier': 'Premium',
        'priceInput': '$5',
        'priceOutput': '$25',
        'priceCache': '$0.50',
        'contextWindow': '400K',
        'contextTier': '128K-500K',
        'maxOutput': '128K',
        'modality': 'Text + Vision',
        'capabilities': 'Tool use, Compaction across windows, Deep coding reasoning, Long-running tasks, Streaming, Function calling',
        'speedTier': 'Slow/Reasoning',
        'latency': 'high',
        'benchmark': 'SWE-Lancer ~70%; TerminalBench top tier',
        'sweBench': '77%',
        'humanEval': '96%',
        'mmlu': '90%',
        'bestFor': 'Multi-hour, cross-file engineering tasks where context compaction matters; enterprise Codex CLI use',
        'knowledgeCutoff': 'Oct 2025',
        'released': 'Nov 2025',
        'websiteUrl': 'https://openai.com/index/gpt-5-1-codex-max/',
        'docsUrl': 'https://platform.openai.com/docs/models/gpt-5.1-codex-max',
    }),
    ('claude-haiku-4-5-fast', 'Claude Haiku 4.5 (Fast)', {
        'provider': 'Anthropic',
        'hosting': 'Closed/API',
        'modelId': 'claude-haiku-4-5-fast',
        'priceTier': 'Budget',
        'priceInput': '$1',
        'priceOutput': '$5',
        'priceCache': '$0.10',
        'contextWindow': '200K',
        'contextTier': '128K-500K',
        'maxOutput': '32K',
        'modality': 'Multimodal (vision)',
        'capabilities': 'Vision, Tool use, Streaming, Structured output, Prompt caching, Low-latency mode',
        'speedTier': 'Fast',
        'latency': 'low',
        'benchmark': 'Best-in-class latency at Haiku-tier intelligence',
        'sweBench': '55%',
        'humanEval': '88%',
        'mmlu': '82%',
        'bestFor': 'High-throughput coding sidekick, autocomplete, batch jobs, and low-latency Claude Code use',
        'knowledgeCutoff': 'Oct 2025',
        'released': 'Oct 2025',
        'websiteUrl': 'https://www.anthropic.com/claude/haiku',
        'docsUrl': 'https://docs.anthropic.com/en/docs/about-claude/models',
    }),
    ('grok-5', 'Grok 5', {
        'provider': 'xAI',
        'hosting': 'Closed/API',
        'modelId': 'grok-5',
        'priceTier': 'Premium',
        'priceInput': '$5',
        'priceOutput': '$25',
        'priceCache': '$0.50',
        'contextWindow': '1M+',
        'contextTier': '500K+',
        'maxOutput': '64K',
        'modality': 'Multimodal (vision)',
        'capabilities': 'Vision, Tool use, Web search, Streaming, Function calling, Real-time X data',
        'speedTier': 'Medium',
        'latency': 'medium',
        'benchmark': 'GPQA, AIME, ARC-AGI competitive',
        'sweBench': '72%',
        'humanEval': '94%',
        'mmlu': '89%',
        'bestFor': 'Real-time web/X context, long-context analysis, and agentic browsing',
        'knowledgeCutoff': 'Dec 2025',
        'released': 'Jan 2026',
        'websiteUrl': 'https://x.ai/grok',
        'docsUrl': 'https://docs.x.ai/docs/models',
    }),
    ('grok-code-fast-2', 'Grok Code Fast 2', {
        'provider': 'xAI',
        'hosting': 'Closed/API',
        'modelId': 'grok-code-fast-2',
        'priceTier': 'Budget',
        'priceInput': '$0.20',
        'priceOutput': '$1.50',
        'priceCache': '$0.02',
        'contextWindow': '256K',
        'contextTier': '128K-500K',
        'maxOutput': '32K',
        'modality': 'Text',
        'capabilities': 'Tool use, Function calling, High-throughput, Code-specialized, Prompt caching',
        'speedTier': 'Fast',
        'latency': 'low',
        'benchmark': 'High SWE-bench at very low cost',
        'sweBench': '65%',
        'humanEval': '91%',
        'mmlu': '85%',
        'bestFor': 'High-volume agentic coding where latency and cost trump max intelligence',
        'knowledgeCutoff': 'Nov 2025',
        'released': 'Dec 2025',
        'websiteUrl': 'https://x.ai/grok',
        'docsUrl': 'https://docs.x.ai/docs/models',
    }),
    ('deepseek-v4', 'DeepSeek V4', {
        'provider': 'DeepSeek',
        'hosting': 'Open/Self-host',
        'modelId': 'deepseek-v4',
        'priceTier': 'Budget',
        'priceInput': '$0.27',
        'priceOutput': '$1.10',
        'priceCache': '$0.07',
        'contextWindow': '256K',
        'contextTier': '128K-500K',
        'maxOutput': '16K',
        'modality': 'Text',
        'capabilities': 'Tool use, MoE architecture, Function calling, Streaming, Prompt caching, Self-host friendly',
        'speedTier': 'Medium',
        'latency': 'medium',
        'benchmark': 'Beats most open-weight models at coding and math',
        'sweBench': '63%',
        'humanEval': '92%',
        'mmlu': '86%',
        'bestFor': 'Low-cost coding LLM with self-host option; strong English + Chinese coding capabilities',
        'knowledgeCutoff': 'Oct 2025',
        'released': 'Nov 2025',
        'websiteUrl': 'https://www.deepseek.com/',
        'docsUrl': 'https://api-docs.deepseek.com/',
    }),
    ('qwen-3-max', 'Qwen 3 Max', {
        'provider': 'Alibaba',
        'hosting': 'Closed/API + Self-host',
        'modelId': 'qwen3-max',
        'priceTier': 'Mid',
        'priceInput': '$1.50',
        'priceOutput': '$6',
        'priceCache': '$0.15',
        'contextWindow': '1M+',
        'contextTier': '500K+',
        'maxOutput': '32K',
        'modality': 'Multimodal (vision)',
        'capabilities': 'Vision, Tool use, Function calling, Streaming, 1M context, Strong multilingual',
        'speedTier': 'Medium',
        'latency': 'medium',
        'benchmark': 'Top on multi-lingual benchmarks and long-context tasks',
        'sweBench': '68%',
        'humanEval': '92%',
        'mmlu': '88%',
        'bestFor': 'Long-context coding, multilingual codebases, China-region deployments',
        'knowledgeCutoff': 'Sep 2025',
        'released': 'Oct 2025',
        'websiteUrl': 'https://qwenlm.ai/',
        'docsUrl': 'https://help.aliyun.com/zh/model-studio/developer-reference/use-qwen-by-api',
    }),
    ('llama-4-behemoth', 'Llama 4 Behemoth', {
        'provider': 'Meta',
        'hosting': 'Open/Self-host',
        'modelId': 'llama-4-behemoth',
        'priceTier': 'Premium',
        'priceInput': '$3',
        'priceOutput': '$15',
        'priceCache': '$0.30',
        'contextWindow': '1M+',
        'contextTier': '500K+',
        'maxOutput': '32K',
        'modality': 'Multimodal (vision)',
        'capabilities': 'Vision, Tool use, MoE, Function calling, Streaming, 2T params',
        'speedTier': 'Slow/Reasoning',
        'latency': 'high',
        'benchmark': 'Frontier open-weight model competitive with closed labs',
        'sweBench': '74%',
        'humanEval': '95%',
        'mmlu': '91%',
        'bestFor': 'Self-hosted frontier reasoning, complex agentic coding, multimodal analysis',
        'knowledgeCutoff': 'Aug 2025',
        'released': 'Nov 2025',
        'websiteUrl': 'https://llama.meta.com/',
        'docsUrl': 'https://llama.meta.com/docs',
    }),
    ('llama-4-scout', 'Llama 4 Scout', {
        'provider': 'Meta',
        'hosting': 'Open/Self-host',
        'modelId': 'llama-4-scout',
        'priceTier': 'Budget',
        'priceInput': '$0.20',
        'priceOutput': '$0.60',
        'priceCache': '$0.04',
        'contextWindow': '10M',
        'contextTier': '500K+',
        'maxOutput': '8K',
        'modality': 'Multimodal (vision)',
        'capabilities': 'Vision, Tool use, MoE, Function calling, 10M context, Single-GPU friendly',
        'speedTier': 'Fast',
        'latency': 'low',
        'benchmark': 'Best long-context open-weight model at this size',
        'sweBench': '52%',
        'humanEval': '88%',
        'mmlu': '82%',
        'bestFor': 'On-prem 10M-token context analysis, doc/codebase RAG without external chunking',
        'knowledgeCutoff': 'Aug 2025',
        'released': 'Apr 2025',
        'websiteUrl': 'https://llama.meta.com/',
        'docsUrl': 'https://llama.meta.com/docs',
    }),
    ('mistral-large-4', 'Mistral Large 4', {
        'provider': 'Mistral',
        'hosting': 'Closed/API + Self-host',
        'modelId': 'mistral-large-4',
        'priceTier': 'Mid',
        'priceInput': '$2',
        'priceOutput': '$8',
        'priceCache': '$0.20',
        'contextWindow': '256K',
        'contextTier': '128K-500K',
        'maxOutput': '32K',
        'modality': 'Multimodal (vision)',
        'capabilities': 'Vision, Tool use, Function calling, Multilingual, Streaming, Prompt caching, EU-hosted',
        'speedTier': 'Medium',
        'latency': 'medium',
        'benchmark': 'Strong on coding + multilingual reasoning',
        'sweBench': '67%',
        'humanEval': '93%',
        'mmlu': '87%',
        'bestFor': 'EU-residency coding workloads, multilingual engineering, GDPR-sensitive deployments',
        'knowledgeCutoff': 'Sep 2025',
        'released': 'Dec 2025',
        'websiteUrl': 'https://mistral.ai/',
        'docsUrl': 'https://docs.mistral.ai/',
    }),
    ('codestral-2', 'Codestral 2', {
        'provider': 'Mistral',
        'hosting': 'Closed/API + Self-host',
        'modelId': 'codestral-2',
        'priceTier': 'Budget',
        'priceInput': '$0.30',
        'priceOutput': '$0.90',
        'priceCache': '$0.05',
        'contextWindow': '256K',
        'contextTier': '128K-500K',
        'maxOutput': '16K',
        'modality': 'Text',
        'capabilities': 'Tool use, Code-specialized, Function calling, Fill-in-the-middle, 80+ languages',
        'speedTier': 'Fast',
        'latency': 'low',
        'benchmark': 'Top latency-vs-quality tradeoff for autocomplete',
        'sweBench': '62%',
        'humanEval': '91%',
        'mmlu': '83%',
        'bestFor': 'In-IDE completions, fill-in-the-middle, code refactoring, BYO-model integrations',
        'knowledgeCutoff': 'Aug 2025',
        'released': 'Oct 2025',
        'websiteUrl': 'https://mistral.ai/news/codestral-2',
        'docsUrl': 'https://docs.mistral.ai/capabilities/code_generation/',
    }),
    ('kimi-k3', 'Kimi K3', {
        'provider': 'Moonshot AI',
        'hosting': 'Closed/API + Self-host',
        'modelId': 'kimi-k3',
        'priceTier': 'Budget',
        'priceInput': '$0.60',
        'priceOutput': '$2.50',
        'priceCache': '$0.10',
        'contextWindow': '2M',
        'contextTier': '500K+',
        'maxOutput': '16K',
        'modality': 'Multimodal (vision)',
        'capabilities': 'Vision, Tool use, Function calling, Long-context retrieval, Agentic tooling, MoE',
        'speedTier': 'Medium',
        'latency': 'medium',
        'benchmark': 'Top open-weight model for agentic coding',
        'sweBench': '70%',
        'humanEval': '93%',
        'mmlu': '87%',
        'bestFor': 'Agentic coding at low cost, ultra-long context, China-region deployments',
        'knowledgeCutoff': 'Oct 2025',
        'released': 'Dec 2025',
        'websiteUrl': 'https://moonshot.cn/',
        'docsUrl': 'https://platform.moonshot.cn/docs',
    }),
    ('glm-5-air', 'GLM 5 Air', {
        'provider': 'Zhipu AI',
        'hosting': 'Open/Self-host',
        'modelId': 'glm-5-air',
        'priceTier': 'Budget',
        'priceInput': '$0.15',
        'priceOutput': '$0.60',
        'priceCache': '$0.02',
        'contextWindow': '128K',
        'contextTier': '128K-500K',
        'maxOutput': '16K',
        'modality': 'Text',
        'capabilities': 'Tool use, Function calling, Streaming, MoE, Single-GPU friendly',
        'speedTier': 'Fast',
        'latency': 'low',
        'benchmark': 'Cheap-and-fast tier; strong code/agent task scores',
        'sweBench': '58%',
        'humanEval': '88%',
        'mmlu': '80%',
        'bestFor': 'Cheap self-hosted coding agent, autocomplete, batch inference at scale',
        'knowledgeCutoff': 'Aug 2025',
        'released': 'Sep 2025',
        'websiteUrl': 'https://zhipuai.cn/',
        'docsUrl': 'https://bigmodel.cn/dev/api',
    }),
    ('hermes-4', 'Hermes 4', {
        'provider': 'Nous Research',
        'hosting': 'Open/Self-host',
        'modelId': 'hermes-4-405b',
        'priceTier': 'Mid',
        'priceInput': '$0.90',
        'priceOutput': '$2.70',
        'priceCache': '$0.10',
        'contextWindow': '128K',
        'contextTier': '128K-500K',
        'maxOutput': '16K',
        'modality': 'Text',
        'capabilities': 'Tool use, Hybrid reasoning, Function calling, Streaming, Steerable persona, Uncensored',
        'speedTier': 'Medium',
        'latency': 'medium',
        'benchmark': 'Strong on reasoning + alignment benchmarks',
        'sweBench': '60%',
        'humanEval': '89%',
        'mmlu': '85%',
        'bestFor': 'Self-hosted assistants with steerable persona and explicit chain-of-thought support',
        'knowledgeCutoff': 'Aug 2025',
        'released': 'Sep 2025',
        'websiteUrl': 'https://nousresearch.com/',
        'docsUrl': 'https://huggingface.co/NousResearch',
    }),
    ('magistral-2', 'Magistral 2', {
        'provider': 'Mistral',
        'hosting': 'Open/Self-host',
        'modelId': 'magistral-2',
        'priceTier': 'Mid',
        'priceInput': '$2',
        'priceOutput': '$5',
        'priceCache': '$0.20',
        'contextWindow': '128K',
        'contextTier': '128K-500K',
        'maxOutput': '32K',
        'modality': 'Text',
        'capabilities': 'Tool use, Extended reasoning, Function calling, Chain-of-thought traces, Multilingual',
        'speedTier': 'Slow/Reasoning',
        'latency': 'high',
        'benchmark': 'Reasoning-tuned open weights with visible chain-of-thought',
        'sweBench': '64%',
        'humanEval': '92%',
        'mmlu': '86%',
        'bestFor': 'Reasoning workloads where chain-of-thought transparency and EU residency matter',
        'knowledgeCutoff': 'Aug 2025',
        'released': 'Nov 2025',
        'websiteUrl': 'https://mistral.ai/news/magistral',
        'docsUrl': 'https://docs.mistral.ai/',
    }),
    ('cohere-command-r-2', 'Command R 2', {
        'provider': 'Cohere',
        'hosting': 'Closed/API + Self-host',
        'modelId': 'command-r-2',
        'priceTier': 'Budget',
        'priceInput': '$0.50',
        'priceOutput': '$1.50',
        'priceCache': '$0.05',
        'contextWindow': '256K',
        'contextTier': '128K-500K',
        'maxOutput': '16K',
        'modality': 'Text',
        'capabilities': 'Tool use, Function calling, Retrieval-tuned, Streaming, Multi-step tool calls, Citations',
        'speedTier': 'Fast',
        'latency': 'low',
        'benchmark': 'Strong RAG and tool-use benchmarks for the price tier',
        'sweBench': '50%',
        'humanEval': '85%',
        'mmlu': '80%',
        'bestFor': 'RAG and tool-using agents in regulated enterprises with on-prem deployment options',
        'knowledgeCutoff': 'Aug 2025',
        'released': 'Oct 2025',
        'websiteUrl': 'https://cohere.com/command',
        'docsUrl': 'https://docs.cohere.com/docs/command-r',
    }),
    ('jamba-1-7', 'Jamba 1.7', {
        'provider': 'AI21 Labs',
        'hosting': 'Closed/API + Self-host',
        'modelId': 'jamba-1.7-large',
        'priceTier': 'Budget',
        'priceInput': '$0.40',
        'priceOutput': '$1.20',
        'priceCache': '$0.05',
        'contextWindow': '256K',
        'contextTier': '128K-500K',
        'maxOutput': '16K',
        'modality': 'Text',
        'capabilities': 'Tool use, Hybrid SSM-Transformer, Function calling, Long-context efficient, RAG-tuned',
        'speedTier': 'Fast',
        'latency': 'low',
        'benchmark': 'Top throughput for long-context RAG at low memory cost',
        'sweBench': '52%',
        'humanEval': '86%',
        'mmlu': '81%',
        'bestFor': 'Long-context RAG with low memory; cost-conscious enterprise deployments',
        'knowledgeCutoff': 'Aug 2025',
        'released': 'Oct 2025',
        'websiteUrl': 'https://www.ai21.com/jamba',
        'docsUrl': 'https://docs.ai21.com/docs/jamba-1-7-models',
    }),
    ('phi-5', 'Phi-5', {
        'provider': 'Microsoft',
        'hosting': 'Open/Self-host',
        'modelId': 'phi-5-mini',
        'priceTier': 'Budget',
        'priceInput': '$0.10',
        'priceOutput': '$0.30',
        'priceCache': '$0.02',
        'contextWindow': '128K',
        'contextTier': '128K-500K',
        'maxOutput': '8K',
        'modality': 'Text',
        'capabilities': 'Tool use, Function calling, Compact, On-device friendly, Reasoning-tuned',
        'speedTier': 'Fast',
        'latency': 'low',
        'benchmark': 'Best-in-class small model on reasoning benchmarks',
        'sweBench': '40%',
        'humanEval': '83%',
        'mmlu': '78%',
        'bestFor': 'On-device AI, edge inference, mobile/embedded coding sidekicks',
        'knowledgeCutoff': 'Aug 2025',
        'released': 'Oct 2025',
        'websiteUrl': 'https://azure.microsoft.com/en-us/products/phi',
        'docsUrl': 'https://learn.microsoft.com/en-us/azure/ai-services/phi',
    }),
    ('nova-premier-2', 'Amazon Nova Premier 2', {
        'provider': 'Amazon',
        'hosting': 'Closed/API',
        'modelId': 'nova-premier-2',
        'priceTier': 'Premium',
        'priceInput': '$3.50',
        'priceOutput': '$15',
        'priceCache': '$0.35',
        'contextWindow': '1M+',
        'contextTier': '500K+',
        'maxOutput': '32K',
        'modality': 'Multimodal (vision)',
        'capabilities': 'Vision, Tool use, Function calling, Streaming, Bedrock-only, Agent-tuned',
        'speedTier': 'Medium',
        'latency': 'medium',
        'benchmark': 'Bedrock-hosted, top among AWS frontier offerings',
        'sweBench': '65%',
        'humanEval': '92%',
        'mmlu': '87%',
        'bestFor': 'AWS-native enterprise agents, Bedrock integrations, long-context analysis',
        'knowledgeCutoff': 'Sep 2025',
        'released': 'Nov 2025',
        'websiteUrl': 'https://aws.amazon.com/nova/',
        'docsUrl': 'https://docs.aws.amazon.com/nova/',
    }),
    ('yi-3-lightning', 'Yi-3 Lightning', {
        'provider': '01.AI',
        'hosting': 'Closed/API + Self-host',
        'modelId': 'yi-3-lightning',
        'priceTier': 'Budget',
        'priceInput': '$0.10',
        'priceOutput': '$0.30',
        'priceCache': '$0.02',
        'contextWindow': '128K',
        'contextTier': '128K-500K',
        'maxOutput': '8K',
        'modality': 'Text',
        'capabilities': 'Tool use, Function calling, Streaming, Bilingual EN/ZH, Compact',
        'speedTier': 'Fast',
        'latency': 'low',
        'benchmark': 'Top low-cost bilingual model',
        'sweBench': '48%',
        'humanEval': '85%',
        'mmlu': '79%',
        'bestFor': 'Cheap, fast bilingual coding tasks and high-volume Chinese-English mixed workloads',
        'knowledgeCutoff': 'Aug 2025',
        'released': 'Sep 2025',
        'websiteUrl': 'https://01.ai/',
        'docsUrl': 'https://platform.01.ai/docs',
    }),
    ('inflection-3', 'Inflection 3', {
        'provider': 'Inflection AI',
        'hosting': 'Closed/API',
        'modelId': 'inflection-3-productivity',
        'priceTier': 'Mid',
        'priceInput': '$2.50',
        'priceOutput': '$10',
        'priceCache': '$0.25',
        'contextWindow': '128K',
        'contextTier': '128K-500K',
        'maxOutput': '16K',
        'modality': 'Text',
        'capabilities': 'Tool use, Function calling, Streaming, Productivity-tuned, On-prem option',
        'speedTier': 'Medium',
        'latency': 'medium',
        'benchmark': 'Enterprise on-prem with competitive coding scores',
        'sweBench': '58%',
        'humanEval': '89%',
        'mmlu': '84%',
        'bestFor': 'Enterprise deployments requiring on-prem AI with productivity tuning',
        'knowledgeCutoff': 'Jul 2025',
        'released': 'Oct 2025',
        'websiteUrl': 'https://inflection.ai/',
        'docsUrl': 'https://developers.inflection.ai/',
    }),
]

# ============================================================================
# INTEGRATION LAYER — new entries
# ============================================================================
INTEGRATION_NEW = [
    ('roo-code', 'Roo Code', {
        'compatibility': 'VS Code, JetBrains, Cursor, Windsurf',
        'pricing': 'Free (BYO API key)',
        'openSource': 'Yes',
        'interface': 'In-editor',
        'setup': 'Low',
        'bestFor': 'Multi-mode autonomous coding agent with BYO model, code/architect/ask/debug modes',
        'capabilities': 'File edits, Terminal commands, Browser use, Multi-mode (Code/Architect/Ask/Debug), MCP, Custom modes, BYO model',
        'modelChoice': 'BYO model',
        'contextHandling': 'Repo-aware',
        'privacy': 'Configurable',
        'released': '2024',
        'websiteUrl': 'https://roocode.com/',
        'docsUrl': 'https://docs.roocode.com/',
    }),
    ('kilocode', 'Kilo Code', {
        'compatibility': 'VS Code, JetBrains',
        'pricing': 'Free (BYO API key)',
        'openSource': 'Yes',
        'interface': 'In-editor',
        'setup': 'Low',
        'bestFor': 'Open-source merge of Roo + Cline aiming at the most powerful BYO agent',
        'capabilities': 'File edits, Terminal commands, Browser use, Multi-mode, MCP, Marketplace, BYO model, Roo + Cline features',
        'modelChoice': 'BYO model',
        'contextHandling': 'Repo-aware',
        'privacy': 'Configurable',
        'released': '2024',
        'websiteUrl': 'https://kilocode.ai/',
        'docsUrl': 'https://kilocode.ai/docs',
    }),
    ('codex-vscode', 'OpenAI Codex (VS Code)', {
        'compatibility': 'VS Code, Cursor, JetBrains',
        'pricing': 'Bundled with ChatGPT Plus/Pro',
        'openSource': 'No',
        'interface': 'In-editor',
        'setup': 'Zero',
        'bestFor': 'OpenAI-first IDE agent powered by GPT-5.1 Codex with deep VS Code integration',
        'capabilities': 'In-editor agent, Multi-file edits, Chat, Voice mode, Cloud sandbox tasks, MCP, Long-running tasks',
        'modelChoice': 'Fixed (OpenAI)',
        'contextHandling': 'Repo-aware',
        'privacy': 'Sent to provider',
        'released': '2025',
        'websiteUrl': 'https://openai.com/codex/',
        'docsUrl': 'https://developers.openai.com/codex/',
    }),
    ('zed-agent', 'Zed Agent', {
        'compatibility': 'Zed only',
        'pricing': 'Freemium',
        'openSource': 'Yes',
        'interface': 'In-editor',
        'setup': 'Zero',
        'bestFor': 'Native AI agent inside Zed with edit prediction, multi-file edits, and MCP support',
        'capabilities': 'Inline completion, Chat, Multi-file edits, Edit prediction, MCP, BYO model, Threads',
        'modelChoice': 'Multiple providers',
        'contextHandling': 'Repo-aware',
        'privacy': 'Configurable',
        'released': '2024',
        'websiteUrl': 'https://zed.dev/agentic',
        'docsUrl': 'https://zed.dev/docs/ai/agent-panel',
    }),
    ('augment', 'Augment Code', {
        'compatibility': 'VS Code, JetBrains, Vim, Neovim',
        'pricing': 'Paid (per-user)',
        'openSource': 'No',
        'interface': 'In-editor',
        'setup': 'Low',
        'bestFor': 'Enterprise codebase-aware AI on massive monorepos with low-latency completions',
        'capabilities': 'Inline completion, Chat, Multi-file edits, Agent, Codebase indexing (200K-file scale), Slack/Jira integrations, SOC 2',
        'modelChoice': 'Fixed',
        'contextHandling': 'Indexed RAG',
        'privacy': 'Sent to provider',
        'released': '2024',
        'websiteUrl': 'https://www.augmentcode.com/',
        'docsUrl': 'https://docs.augmentcode.com/',
    }),
    ('plandex', 'Plandex', {
        'compatibility': 'CLI (terminal)',
        'pricing': 'Freemium (BYO API key)',
        'openSource': 'Yes',
        'interface': 'Terminal/CLI',
        'setup': 'Low',
        'bestFor': 'Long-horizon CLI coding tasks across large projects with version-controlled context',
        'capabilities': 'CLI agent, Branching, Diff review, Multi-file edits, Branch-based workflow, BYO model, Long context',
        'modelChoice': 'BYO model',
        'contextHandling': 'Repo-aware',
        'privacy': 'Configurable',
        'released': '2024',
        'websiteUrl': 'https://plandex.ai/',
        'docsUrl': 'https://docs.plandex.ai/',
    }),
    ('opencode', 'OpenCode', {
        'compatibility': 'Terminal (CLI)',
        'pricing': 'Free (BYO API key)',
        'openSource': 'Yes',
        'interface': 'Terminal/CLI',
        'setup': 'Low',
        'bestFor': 'Open-source terminal-first coding agent, comparable to Claude Code with BYO models',
        'capabilities': 'CLI agent, Multi-file edits, MCP, Shell access, BYO model, Plan/Act modes, Provider-agnostic',
        'modelChoice': 'BYO model',
        'contextHandling': 'Repo-aware',
        'privacy': 'Configurable',
        'released': '2024',
        'websiteUrl': 'https://opencode.ai/',
        'docsUrl': 'https://opencode.ai/docs',
    }),
    ('gemini-cli', 'Gemini CLI', {
        'compatibility': 'Terminal (CLI)',
        'pricing': 'Free (Gemini API quota)',
        'openSource': 'Yes',
        'interface': 'Terminal/CLI',
        'setup': 'Low',
        'bestFor': 'Free terminal agent powered by Gemini 3 Pro with generous quota for solo developers',
        'capabilities': 'CLI agent, Shell access, File edits, MCP, Long context (1M+), Tool use, Search grounding',
        'modelChoice': 'Fixed (Gemini)',
        'contextHandling': 'Repo-aware',
        'privacy': 'Sent to provider',
        'released': '2025',
        'websiteUrl': 'https://github.com/google-gemini/gemini-cli',
        'docsUrl': 'https://github.com/google-gemini/gemini-cli/blob/main/docs/index.md',
    }),
    ('amp', 'Amp (Sourcegraph)', {
        'compatibility': 'VS Code, JetBrains, CLI',
        'pricing': 'Freemium',
        'openSource': 'No',
        'interface': 'In-editor',
        'setup': 'Low',
        'bestFor': 'Sourcegraph successor to Cody; agentic coding with deep code search and team mode',
        'capabilities': 'Agent, Chat, Multi-file edits, Code search (Sourcegraph), MCP, Threads, Team sharing',
        'modelChoice': 'Multiple providers',
        'contextHandling': 'Indexed RAG',
        'privacy': 'Configurable',
        'released': '2025',
        'websiteUrl': 'https://ampcode.com/',
        'docsUrl': 'https://ampcode.com/manual',
    }),
    ('warp-ai', 'Warp Agent Mode', {
        'compatibility': 'Warp terminal (macOS, Linux, Windows)',
        'pricing': 'Freemium',
        'openSource': 'No',
        'interface': 'Terminal/CLI',
        'setup': 'Zero',
        'bestFor': 'Terminal-first AI agent inside the Warp shell with shared command history and code blocks',
        'capabilities': 'Agent mode, Inline command suggestions, Shell-aware chat, Workflows, Team sharing, MCP',
        'modelChoice': 'Multiple providers',
        'contextHandling': 'Shell-aware',
        'privacy': 'Configurable',
        'released': '2024',
        'websiteUrl': 'https://www.warp.dev/agent-mode',
        'docsUrl': 'https://docs.warp.dev/agents/agent-mode',
    }),
    ('cody-vscode', 'Cody (Enterprise)', {
        'compatibility': 'VS Code, JetBrains, Visual Studio, Sourcegraph Web',
        'pricing': 'Paid (enterprise)',
        'openSource': 'Yes',
        'interface': 'In-editor',
        'setup': 'Low',
        'bestFor': 'Enterprise teams already on Sourcegraph wanting code search + AI in one platform',
        'capabilities': 'Chat, Inline completion, Multi-file edits, Sourcegraph search context, Custom models, Audit logs, SAML SSO',
        'modelChoice': 'Multiple providers',
        'contextHandling': 'Indexed RAG',
        'privacy': 'Configurable',
        'released': '2023',
        'websiteUrl': 'https://sourcegraph.com/cody',
        'docsUrl': 'https://sourcegraph.com/docs/cody',
    }),
    ('cursor-cli', 'Cursor CLI', {
        'compatibility': 'Terminal (CLI)',
        'pricing': 'Freemium (Cursor subscription)',
        'openSource': 'No',
        'interface': 'Terminal/CLI',
        'setup': 'Zero',
        'bestFor': 'Cursor users wanting headless agent runs from the terminal and CI pipelines',
        'capabilities': 'Headless agent, Background tasks, Cursor model picker, MCP, Shell access',
        'modelChoice': 'Multiple providers',
        'contextHandling': 'Repo-aware',
        'privacy': 'Sent to provider',
        'released': '2025',
        'websiteUrl': 'https://cursor.com/cli',
        'docsUrl': 'https://docs.cursor.com/cli',
    }),
    ('crush', 'Crush (Charm)', {
        'compatibility': 'Terminal (CLI)',
        'pricing': 'Free (BYO API key)',
        'openSource': 'Yes',
        'interface': 'Terminal/CLI',
        'setup': 'Low',
        'bestFor': 'Beautiful TUI coding agent with BYO model and session sharing',
        'capabilities': 'CLI agent, TUI, Sessions, BYO model, MCP, Plan/Act modes, Shell access',
        'modelChoice': 'BYO model',
        'contextHandling': 'Repo-aware',
        'privacy': 'Configurable',
        'released': '2025',
        'websiteUrl': 'https://charm.land/crush',
        'docsUrl': 'https://github.com/charmbracelet/crush',
    }),
]

# ============================================================================
# CONTEXT / RAG LAYER — new entries
# ============================================================================
CONTEXT_NEW = [
    ('turbopuffer', 'turbopuffer', {
        'indexLimit': 'Very large',
        'hosting': 'Cloud',
        'staleness': 'manual',
        'setup': 'Low',
        'openSource': 'No',
        'bestFor': 'Cheap, fast object-storage-backed vector + full-text search for AI agents at scale',
        'capabilities': 'Embedding search, Full-text BM25, Hybrid search, Namespaces, Metadata filtering, Serverless, Object-store backed',
        'indexType': 'Embeddings + Hybrid',
        'updateMode': 'On-demand',
        'privacy': 'Cloud index',
        'released': '2024',
        'websiteUrl': 'https://turbopuffer.com/',
        'docsUrl': 'https://turbopuffer.com/docs',
    }),
    ('vespa', 'Vespa', {
        'indexLimit': 'Very large',
        'hosting': 'Both',
        'staleness': 'manual',
        'setup': 'High',
        'openSource': 'Yes',
        'bestFor': 'Production-grade hybrid search (vector + BM25 + ranking) at billions-of-docs scale',
        'capabilities': 'Embedding search, BM25, Hybrid ranking, Tensor expressions, Real-time indexing, Self-host or Vespa Cloud',
        'indexType': 'Embeddings + BM25',
        'updateMode': 'Real-time',
        'privacy': 'Configurable',
        'released': '2017',
        'websiteUrl': 'https://vespa.ai/',
        'docsUrl': 'https://docs.vespa.ai/',
    }),
    ('elasticsearch-vector', 'Elasticsearch (Vector)', {
        'indexLimit': 'Very large',
        'hosting': 'Both',
        'staleness': 'manual',
        'setup': 'Medium',
        'openSource': 'Yes',
        'bestFor': 'Adding vector search to existing Elastic deployments with hybrid BM25 + ANN',
        'capabilities': 'Embedding search, BM25, Hybrid search, kNN, ELSER sparse embeddings, ESQL',
        'indexType': 'Embeddings + BM25',
        'updateMode': 'Real-time',
        'privacy': 'Configurable',
        'released': '2010 (vector since 2022)',
        'websiteUrl': 'https://www.elastic.co/elasticsearch/vector-database',
        'docsUrl': 'https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html',
    }),
    ('mongodb-atlas-vector', 'MongoDB Atlas Vector Search', {
        'indexLimit': 'Very large',
        'hosting': 'Cloud',
        'staleness': 'manual',
        'setup': 'Low',
        'openSource': 'No',
        'bestFor': 'Vector RAG on top of an existing MongoDB Atlas operational database',
        'capabilities': 'Embedding search, Hybrid (with Atlas Search), Filters, Drop-in MongoDB API, Auto-scaling',
        'indexType': 'Embeddings',
        'updateMode': 'Real-time',
        'privacy': 'Cloud index',
        'released': '2023',
        'websiteUrl': 'https://www.mongodb.com/products/platform/atlas-vector-search',
        'docsUrl': 'https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-overview/',
    }),
    ('supabase-vector', 'Supabase Vector', {
        'indexLimit': 'Large',
        'hosting': 'Cloud',
        'staleness': 'manual',
        'setup': 'Low',
        'openSource': 'Yes',
        'bestFor': 'Postgres-native vector RAG that piggybacks on Supabase Auth, Storage, and Realtime',
        'capabilities': 'Embedding search, pgvector, Edge Functions, Auth integration, Hosted Postgres',
        'indexType': 'Embeddings',
        'updateMode': 'Real-time',
        'privacy': 'Configurable',
        'released': '2023',
        'websiteUrl': 'https://supabase.com/vector',
        'docsUrl': 'https://supabase.com/docs/guides/ai',
    }),
    ('marqo', 'Marqo', {
        'indexLimit': 'Large',
        'hosting': 'Both',
        'staleness': 'manual',
        'setup': 'Low',
        'openSource': 'Yes',
        'bestFor': 'End-to-end vector search with built-in embedding generation and tensor pipelines',
        'capabilities': 'Embedding search, Built-in embedding models, Multi-modal, Tensor pipelines, Hybrid',
        'indexType': 'Embeddings + Hybrid',
        'updateMode': 'On-demand',
        'privacy': 'Configurable',
        'released': '2022',
        'websiteUrl': 'https://marqo.ai/',
        'docsUrl': 'https://docs.marqo.ai/',
    }),
    ('cognee', 'Cognee', {
        'indexLimit': 'You manage',
        'hosting': 'Both',
        'staleness': 'auto',
        'setup': 'Low',
        'openSource': 'Yes',
        'bestFor': 'Open-source memory framework that builds knowledge graphs over agent state and code',
        'capabilities': 'Knowledge graphs, Semantic search, Auto compression, Episodic + semantic memory, Pluggable vector + graph DB',
        'indexType': 'Graph + Embeddings',
        'updateMode': 'Real-time',
        'privacy': 'Configurable',
        'released': '2024',
        'websiteUrl': 'https://www.cognee.ai/',
        'docsUrl': 'https://docs.cognee.ai/',
    }),
    ('letta', 'Letta', {
        'indexLimit': 'You manage',
        'hosting': 'Both',
        'staleness': 'auto',
        'setup': 'Medium',
        'openSource': 'Yes',
        'bestFor': 'Stateful agents with self-editing long-term memory built on the MemGPT pattern',
        'capabilities': 'Long-term memory, Tool use, Recall memory, Archival memory, MemGPT-style paging, Letta server',
        'indexType': 'Embeddings + Structured',
        'updateMode': 'Real-time',
        'privacy': 'Configurable',
        'released': '2024',
        'websiteUrl': 'https://www.letta.com/',
        'docsUrl': 'https://docs.letta.com/',
    }),
    ('zep', 'Zep', {
        'indexLimit': 'You manage',
        'hosting': 'Both',
        'staleness': 'auto',
        'setup': 'Low',
        'openSource': 'Yes',
        'bestFor': 'Memory layer purpose-built for chat agents with temporal knowledge graphs and dedupe',
        'capabilities': 'Long-term memory, Temporal knowledge graph, Fact extraction, Session summaries, REST/SDK, BYO LLM',
        'indexType': 'Graph + Embeddings',
        'updateMode': 'Real-time',
        'privacy': 'Configurable',
        'released': '2023',
        'websiteUrl': 'https://www.getzep.com/',
        'docsUrl': 'https://help.getzep.com/',
    }),
    ('augment-context', 'Augment Context Engine', {
        'indexLimit': 'Very large',
        'hosting': 'Cloud',
        'staleness': 'auto',
        'setup': 'Low',
        'openSource': 'No',
        'bestFor': 'Enterprise-scale codebase context (200K+ files) with low-latency retrieval and PII filtering',
        'capabilities': 'Code-aware search, Hybrid retrieval, Real-time indexing, SOC 2, SSO, Repo + ticket + docs sync',
        'indexType': 'AST + Embeddings',
        'updateMode': 'Real-time',
        'privacy': 'Configurable',
        'released': '2024',
        'websiteUrl': 'https://www.augmentcode.com/',
        'docsUrl': 'https://docs.augmentcode.com/',
    }),
    ('cocoindex', 'CocoIndex', {
        'indexLimit': 'Large',
        'hosting': 'Both',
        'staleness': 'auto',
        'setup': 'Low',
        'openSource': 'Yes',
        'bestFor': 'Open-source incremental data flow indexing for codebases and docs with real-time updates',
        'capabilities': 'Incremental indexing, Codebase/doc indexing, Real-time updates, Python-first, Pluggable backends',
        'indexType': 'Embeddings',
        'updateMode': 'Real-time',
        'privacy': 'Configurable',
        'released': '2024',
        'websiteUrl': 'https://cocoindex.io/',
        'docsUrl': 'https://cocoindex.io/docs',
    }),
    ('sweep-index', 'Sweep Index', {
        'indexLimit': 'Large',
        'hosting': 'Cloud',
        'staleness': 'auto',
        'setup': 'Low',
        'openSource': 'No',
        'bestFor': 'Codebase context engine tuned for AI PR generation and code modification',
        'capabilities': 'Code-aware search, Symbol graph, Real-time indexing, GitHub-native, PR-aware',
        'indexType': 'AST + Embeddings',
        'updateMode': 'Real-time',
        'privacy': 'Cloud index',
        'released': '2023',
        'websiteUrl': 'https://sweep.dev/',
        'docsUrl': 'https://docs.sweep.dev/',
    }),
]

# ============================================================================
# AGENT LAYER — new entries
# ============================================================================
AGENT_NEW = [
    ('codex-cloud', 'OpenAI Codex (Cloud)', {
        'notes': 'Async cloud agent that runs long tasks in OpenAI sandbox',
        'autonomy': 'Autonomous',
        'interface': 'Web / In-editor',
        'openSource': 'No',
        'cost': 'Bundled with ChatGPT Plus/Pro/Team',
        'setup': 'Zero',
        'bestFor': 'Background async tasks (issue triage, refactors, doc generation) running in a managed cloud sandbox',
        'capabilities': 'Cloud sandbox, Multi-step planning, Long-running tasks, PR generation, GitHub integration, Voice, MCP',
        'modelChoice': 'Fixed (OpenAI)',
        'guardrails': 'Sandboxed',
        'released': '2025',
        'websiteUrl': 'https://openai.com/codex/',
        'docsUrl': 'https://developers.openai.com/codex/cloud',
    }),
    ('jules', 'Jules (Google)', {
        'notes': 'Google autonomous coding agent powered by Gemini, GitHub-native',
        'autonomy': 'Autonomous',
        'interface': 'Web / GitHub',
        'openSource': 'No',
        'cost': 'Freemium',
        'setup': 'Zero',
        'bestFor': 'GitHub issue-driven async coding with managed cloud sandbox and PR output',
        'capabilities': 'Cloud sandbox, GitHub integration, Multi-step planning, PR generation, Test execution, Long-running tasks',
        'modelChoice': 'Fixed (Gemini)',
        'guardrails': 'Sandboxed',
        'released': '2025',
        'websiteUrl': 'https://jules.google/',
        'docsUrl': 'https://jules.google/docs',
    }),
    ('factory-droid', 'Factory Droid', {
        'notes': 'Enterprise multi-agent coding platform with org-wide context',
        'autonomy': 'Autonomous',
        'interface': 'Web / In-editor',
        'openSource': 'No',
        'cost': 'Paid (enterprise)',
        'setup': 'Medium',
        'bestFor': 'Enterprise teams wanting multi-droid orchestration across repos, tickets, and incidents',
        'capabilities': 'Multi-agent orchestration, Repo + Jira + Slack context, PR generation, On-call droids, Long-running tasks',
        'modelChoice': 'Multiple providers',
        'guardrails': 'Approval gates',
        'released': '2024',
        'websiteUrl': 'https://www.factory.ai/',
        'docsUrl': 'https://docs.factory.ai/',
    }),
    ('cursor-bg-agent', 'Cursor Background Agent', {
        'notes': 'Cloud-side parallel agents triggered from Cursor (web + mobile)',
        'autonomy': 'Autonomous',
        'interface': 'Web / Mobile / In-editor',
        'openSource': 'No',
        'cost': 'Bundled with Cursor Pro',
        'setup': 'Zero',
        'bestFor': 'Spinning up many parallel agents from Cursor that run async in the cloud and return PRs',
        'capabilities': 'Cloud sandbox, Parallel agents, Mobile UI, PR generation, MCP, Long-running tasks',
        'modelChoice': 'Multiple providers',
        'guardrails': 'Sandboxed',
        'released': '2025',
        'websiteUrl': 'https://cursor.com/background-agents',
        'docsUrl': 'https://docs.cursor.com/background-agent',
    }),
    ('claude-code-sdk', 'Claude Code SDK Agent', {
        'notes': 'Programmatic Claude Code agents in TS/Python with full tool harness',
        'autonomy': 'Autonomous',
        'interface': 'Framework/SDK',
        'openSource': 'Yes',
        'cost': 'BYO API key',
        'setup': 'Low',
        'bestFor': 'Embedding the Claude Code agent loop into custom apps, CI, or background workers',
        'capabilities': 'Tool use, Multi-step planning, MCP, Subagents, Sessions, Hooks, Custom skills',
        'modelChoice': 'Multiple providers (Claude default)',
        'guardrails': 'Approval gates',
        'released': '2025',
        'websiteUrl': 'https://docs.claude.com/en/api/agent-sdk/overview',
        'docsUrl': 'https://docs.claude.com/en/api/agent-sdk/overview',
    }),
    ('mastra', 'Mastra', {
        'notes': 'TS-first agent framework with workflows, memory, eval, and deploy',
        'autonomy': 'Autonomous',
        'interface': 'Framework/SDK',
        'openSource': 'Yes',
        'cost': 'BYO API key',
        'setup': 'Low',
        'bestFor': 'TypeScript developers building multi-step agents with workflows, RAG, evals, and deploys',
        'capabilities': 'Workflows, Memory, RAG, Evals, Telemetry, MCP, Voice, Deploy adapters, BYO model',
        'modelChoice': 'BYO model',
        'guardrails': 'Approval gates',
        'released': '2024',
        'websiteUrl': 'https://mastra.ai/',
        'docsUrl': 'https://mastra.ai/docs',
    }),
    ('agno', 'Agno (Phidata)', {
        'notes': 'Python multi-agent framework focused on simplicity and speed',
        'autonomy': 'Autonomous',
        'interface': 'Framework/SDK',
        'openSource': 'Yes',
        'cost': 'BYO API key',
        'setup': 'Low',
        'bestFor': 'Lightweight Python multi-agent systems with built-in storage, memory, and tools',
        'capabilities': 'Multi-agent, Memory, Storage, RAG, Knowledge, Workflows, Tools, BYO model',
        'modelChoice': 'BYO model',
        'guardrails': '-',
        'released': '2024',
        'websiteUrl': 'https://www.agno.com/',
        'docsUrl': 'https://docs.agno.com/',
    }),
    ('langchain-agent-core', 'LangChain (Agent Core)', {
        'notes': 'Mature framework for chaining LLMs, tools, and retrieval',
        'autonomy': 'Semi-autonomous',
        'interface': 'Framework/SDK',
        'openSource': 'Yes',
        'cost': 'BYO API key',
        'setup': 'Medium',
        'bestFor': 'Composable chains, RAG, and tool-using agents with deep ecosystem integrations',
        'capabilities': 'Chains, Agents, Tool use, RAG, Memory, LangServe, LangSmith eval, BYO model',
        'modelChoice': 'BYO model',
        'guardrails': '-',
        'released': '2022',
        'websiteUrl': 'https://www.langchain.com/',
        'docsUrl': 'https://python.langchain.com/docs/',
    }),
    ('semantic-kernel', 'Semantic Kernel', {
        'notes': 'Microsoft .NET/Python SDK for orchestrating LLMs and plugins',
        'autonomy': 'Semi-autonomous',
        'interface': 'Framework/SDK',
        'openSource': 'Yes',
        'cost': 'BYO API key',
        'setup': 'Medium',
        'bestFor': 'Enterprise .NET / Python teams orchestrating LLMs with plugins, planners, and memory',
        'capabilities': 'Plugins, Planners, Memory, RAG, Tool use, .NET + Python + Java SDKs, Azure-friendly',
        'modelChoice': 'BYO model',
        'guardrails': 'Approval gates',
        'released': '2023',
        'websiteUrl': 'https://aka.ms/semantic-kernel',
        'docsUrl': 'https://learn.microsoft.com/en-us/semantic-kernel/overview/',
    }),
    ('opendevin', 'OpenDevin (legacy)', {
        'notes': 'Original community fork that became OpenHands',
        'autonomy': 'Autonomous',
        'interface': 'In-editor',
        'openSource': 'Yes',
        'cost': 'BYO API key',
        'setup': 'Medium',
        'bestFor': 'Reference implementation of the original Devin-style agent loop',
        'capabilities': 'Tool use, Multi-step planning, Browser, Shell, Git, File editing, Sandboxed execution',
        'modelChoice': 'BYO model',
        'guardrails': 'Sandboxed',
        'released': '2024',
        'websiteUrl': 'https://github.com/OpenDevin/OpenDevin',
        'docsUrl': 'https://docs.all-hands.dev/',
    }),
    ('bolt-new', 'Bolt.new (StackBlitz)', {
        'notes': 'Browser-based AI agent for full-stack app generation with WebContainers',
        'autonomy': 'Autonomous',
        'interface': 'Web',
        'openSource': 'Yes',
        'cost': 'Freemium',
        'setup': 'Zero',
        'bestFor': 'Prompt-to-app generation in the browser, instant deploy, full-stack JS/TS scaffolds',
        'capabilities': 'WebContainer sandbox, Browser-native execution, Multi-file edits, Deploy, Templates, BYO model',
        'modelChoice': 'Multiple providers',
        'guardrails': 'Sandboxed',
        'released': '2024',
        'websiteUrl': 'https://bolt.new/',
        'docsUrl': 'https://support.bolt.new/',
    }),
    ('lovable', 'Lovable', {
        'notes': 'Prompt-to-product AI agent generating full apps with Supabase integration',
        'autonomy': 'Autonomous',
        'interface': 'Web',
        'openSource': 'No',
        'cost': 'Freemium',
        'setup': 'Zero',
        'bestFor': 'Non-developers and founders building MVPs with React + Supabase from natural-language prompts',
        'capabilities': 'Full-app generation, GitHub sync, Supabase integration, One-click deploy, Visual editing',
        'modelChoice': 'Fixed',
        'guardrails': 'Sandboxed',
        'released': '2024',
        'websiteUrl': 'https://lovable.dev/',
        'docsUrl': 'https://docs.lovable.dev/',
    }),
    ('replit-agent-3', 'Replit Agent 3', {
        'notes': 'Latest Replit agent with autonomous test loops and deploy',
        'autonomy': 'Autonomous',
        'interface': 'Web',
        'openSource': 'No',
        'cost': 'Paid (Replit Core)',
        'setup': 'Zero',
        'bestFor': 'In-browser autonomous app generation with built-in deploy, DB, and test agents',
        'capabilities': 'Multi-step planning, Tool use, Long-running tasks, Auto-testing, Auto-deploy, Browser preview, Shell',
        'modelChoice': 'Fixed',
        'guardrails': 'Sandboxed',
        'released': '2025',
        'websiteUrl': 'https://replit.com/ai',
        'docsUrl': 'https://docs.replit.com/replitai/agent',
    }),
    ('all-hands-cloud', 'All Hands Cloud', {
        'notes': 'Hosted OpenHands agent as a managed cloud service',
        'autonomy': 'Autonomous',
        'interface': 'Web / GitHub',
        'openSource': 'Yes (agent)',
        'cost': 'Paid',
        'setup': 'Zero',
        'bestFor': 'Teams wanting OpenHands without managing their own runtime; GitHub-native triggers',
        'capabilities': 'Tool use, Multi-step planning, Browser, Shell, Git, GitHub triggers, PR generation, Sandboxed',
        'modelChoice': 'Multiple providers',
        'guardrails': 'Sandboxed',
        'released': '2025',
        'websiteUrl': 'https://www.all-hands.dev/',
        'docsUrl': 'https://docs.all-hands.dev/usage/cloud',
    }),
]

# ============================================================================
# OTHERS LAYER — new entries
# ============================================================================
OTHERS_NEW = [
    ('vercel', 'Vercel', {
        'category': 'Deployment / hosting',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Zero',
        'interface': 'Web / CLI',
        'capabilities': 'Edge deploy, Serverless functions, AI Gateway, KV/Postgres/Blob, Preview deploys, Analytics',
        'bestFor': 'Frontend and Next.js hosting with instant previews and AI SDK integration',
        'languages': 'JS, TS, Python, Go, more',
        'released': '2015',
        'notes': 'Default hosting for Next.js; tightly integrated with v0 and the AI SDK.',
        'websiteUrl': 'https://vercel.com/',
        'docsUrl': 'https://vercel.com/docs',
    }),
    ('netlify', 'Netlify', {
        'category': 'Deployment / hosting',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Zero',
        'interface': 'Web / CLI',
        'capabilities': 'Edge deploy, Serverless functions, Forms, Identity, Edge functions, Preview deploys, Blobs',
        'bestFor': 'JAMstack hosting with edge functions, identity, and form handling',
        'languages': 'JS, TS, Go',
        'released': '2014',
        'notes': 'Strong git-based deploy story and form / identity primitives for static sites.',
        'websiteUrl': 'https://www.netlify.com/',
        'docsUrl': 'https://docs.netlify.com/',
    }),
    ('cloudflare-workers', 'Cloudflare Workers', {
        'category': 'Deployment / hosting',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Low',
        'interface': 'Web / CLI / Wrangler',
        'capabilities': 'Edge compute, Durable Objects, KV, R2, D1, Workers AI, Vectorize, Queues',
        'bestFor': 'Globally distributed edge compute, low-latency APIs, and serverless AI inference',
        'languages': 'JS, TS, Python, Rust',
        'released': '2017',
        'notes': 'Workers + Vectorize + R2 is a serious DIY stack for AI agents at the edge.',
        'websiteUrl': 'https://workers.cloudflare.com/',
        'docsUrl': 'https://developers.cloudflare.com/workers/',
    }),
    ('railway', 'Railway', {
        'category': 'Deployment / hosting',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Zero',
        'interface': 'Web / CLI',
        'capabilities': 'Auto-deploy from Git, Databases (Postgres, MySQL, Redis), Variables, Volumes, Templates',
        'bestFor': 'Quickly deploying full-stack apps and databases without managing infra',
        'languages': 'All (via buildpacks)',
        'released': '2020',
        'notes': 'Heroku-style developer experience with modern primitives and per-minute billing.',
        'websiteUrl': 'https://railway.com/',
        'docsUrl': 'https://docs.railway.com/',
    }),
    ('render', 'Render', {
        'category': 'Deployment / hosting',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Low',
        'interface': 'Web / CLI',
        'capabilities': 'Auto-deploy from Git, Web Services, Background workers, Cron jobs, Postgres, Redis, Private services',
        'bestFor': 'Production-leaning Heroku alternative with predictable pricing and managed databases',
        'languages': 'All (via Dockerfiles)',
        'released': '2018',
        'notes': 'Predictable per-service pricing and integrated managed databases.',
        'websiteUrl': 'https://render.com/',
        'docsUrl': 'https://render.com/docs',
    }),
    ('fly-io', 'Fly.io', {
        'category': 'Deployment / hosting',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Low',
        'interface': 'CLI / Web',
        'capabilities': 'Global Anycast, Firecracker VMs, Postgres, Volumes, GPU machines, Litestream-friendly',
        'bestFor': 'Multi-region apps and Postgres replicas with full-VM isolation',
        'languages': 'All (via Dockerfiles)',
        'released': '2017',
        'notes': 'Run real Linux VMs near your users; great fit for latency-sensitive apps and AI inference.',
        'websiteUrl': 'https://fly.io/',
        'docsUrl': 'https://fly.io/docs/',
    }),
    ('supabase', 'Supabase', {
        'category': 'Backend / BaaS',
        'pricing': 'Freemium',
        'hosting': 'Both',
        'openSource': 'Yes',
        'setup': 'Low',
        'interface': 'Web / CLI / SDK',
        'capabilities': 'Postgres, Auth, Realtime, Storage, Edge Functions, Vector, AI Studio',
        'bestFor': 'Open-source Firebase alternative with Postgres-native auth, storage, and realtime',
        'languages': 'All (via REST/SDK)',
        'released': '2020',
        'notes': 'Default Postgres backend for AI app generators; pairs well with Vercel, Lovable, Bolt.new.',
        'websiteUrl': 'https://supabase.com/',
        'docsUrl': 'https://supabase.com/docs',
    }),
    ('neon', 'Neon', {
        'category': 'Database',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'Yes (engine)',
        'setup': 'Zero',
        'interface': 'Web / CLI / SDK',
        'capabilities': 'Serverless Postgres, Branching, Auto-scaling, Storage-compute separation, pgvector',
        'bestFor': 'Postgres for AI agents that need ephemeral branches per task or PR',
        'languages': 'All (Postgres clients)',
        'released': '2022',
        'notes': 'Branching Postgres is a killer feature for AI agents that need isolated DB state per task.',
        'websiteUrl': 'https://neon.com/',
        'docsUrl': 'https://neon.com/docs',
    }),
    ('planetscale', 'PlanetScale', {
        'category': 'Database',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Low',
        'interface': 'Web / CLI',
        'capabilities': 'Serverless MySQL, Vitess-based, Branching, Deploy requests, Insights, Boost cache',
        'bestFor': 'High-scale MySQL with Git-style branching and zero-downtime schema changes',
        'languages': 'All (MySQL clients)',
        'released': '2021',
        'notes': 'Vitess under the hood; strong fit for high-traffic apps that need horizontal scale.',
        'websiteUrl': 'https://planetscale.com/',
        'docsUrl': 'https://planetscale.com/docs',
    }),
    ('turso', 'Turso', {
        'category': 'Database',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'Yes (engine)',
        'setup': 'Zero',
        'interface': 'CLI / SDK',
        'capabilities': 'Edge SQLite (libSQL), Embedded replicas, Multi-tenant, Branching, Sync',
        'bestFor': 'Edge-deployed SQLite with embedded read replicas for low-latency reads',
        'languages': 'All (SQLite clients)',
        'released': '2023',
        'notes': 'Embedded replicas make local-first apps and edge AI agents fast and offline-tolerant.',
        'websiteUrl': 'https://turso.tech/',
        'docsUrl': 'https://docs.turso.tech/',
    }),
    ('mcp-registry', 'MCP Registry', {
        'category': 'Tooling',
        'pricing': 'Free',
        'hosting': 'Cloud',
        'openSource': 'Yes',
        'setup': 'Low',
        'interface': 'Web / CLI',
        'capabilities': 'MCP server discovery, Versioning, Capability metadata, Manifest validation',
        'bestFor': 'Discovering and installing Model Context Protocol servers across agents',
        'languages': 'All (MCP-compatible)',
        'released': '2025',
        'notes': 'Central discovery surface for the Model Context Protocol ecosystem.',
        'websiteUrl': 'https://registry.modelcontextprotocol.io/',
        'docsUrl': 'https://modelcontextprotocol.io/',
    }),
    ('openrouter', 'OpenRouter', {
        'category': 'LLM gateway',
        'pricing': 'Pay-per-token',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Zero',
        'interface': 'API / Web',
        'capabilities': 'Single API for 200+ LLMs, Routing, Fallbacks, Caching, Spend limits, Provider rankings',
        'bestFor': 'BYO-model agents that want a single API for OpenAI, Anthropic, Google, Mistral, etc.',
        'languages': 'All (REST API)',
        'released': '2023',
        'notes': 'Drop-in OpenAI-compatible endpoint covering 200+ models with automatic failover.',
        'websiteUrl': 'https://openrouter.ai/',
        'docsUrl': 'https://openrouter.ai/docs',
    }),
    ('portkey', 'Portkey', {
        'category': 'LLM gateway',
        'pricing': 'Freemium',
        'hosting': 'Both',
        'openSource': 'Yes',
        'setup': 'Low',
        'interface': 'API / Web',
        'capabilities': 'LLM gateway, Observability, Caching, Guardrails, Prompt management, Routing, Budgets',
        'bestFor': 'Production LLM apps needing reliability, observability, and prompt governance',
        'languages': 'All (REST API)',
        'released': '2023',
        'notes': 'Combines a gateway with prompt versioning, evals, and guardrails for enterprise teams.',
        'websiteUrl': 'https://portkey.ai/',
        'docsUrl': 'https://portkey.ai/docs',
    }),
    ('langsmith', 'LangSmith', {
        'category': 'Observability / eval',
        'pricing': 'Freemium',
        'hosting': 'Both',
        'openSource': 'No',
        'setup': 'Low',
        'interface': 'Web / SDK',
        'capabilities': 'Trace logging, Dataset eval, Prompt versioning, Annotation, Online evals, Cost tracking',
        'bestFor': 'Debugging and evaluating LangChain/LangGraph apps and agent traces',
        'languages': 'Python, JS/TS',
        'released': '2023',
        'notes': 'Closest tie-in to the LangChain ecosystem; works with any framework via the SDK.',
        'websiteUrl': 'https://www.langchain.com/langsmith',
        'docsUrl': 'https://docs.smith.langchain.com/',
    }),
    ('helicone', 'Helicone', {
        'category': 'Observability / eval',
        'pricing': 'Freemium',
        'hosting': 'Both',
        'openSource': 'Yes',
        'setup': 'Low',
        'interface': 'Web / Proxy / SDK',
        'capabilities': 'LLM observability, Caching, Rate limits, Cost tracking, Sessions, Evals, Prompt versioning',
        'bestFor': 'Open-source LLM observability with one-line setup as a drop-in proxy',
        'languages': 'All (REST API)',
        'released': '2023',
        'notes': 'Lightweight observability via a header swap; OSS server runs anywhere.',
        'websiteUrl': 'https://www.helicone.ai/',
        'docsUrl': 'https://docs.helicone.ai/',
    }),
    ('langfuse', 'Langfuse', {
        'category': 'Observability / eval',
        'pricing': 'Freemium',
        'hosting': 'Both',
        'openSource': 'Yes',
        'setup': 'Low',
        'interface': 'Web / SDK',
        'capabilities': 'Tracing, Prompt management, Evals, Datasets, Annotation, Cost tracking, Self-hostable',
        'bestFor': 'OSS LLM observability that works with any framework; strong self-host story',
        'languages': 'Python, JS/TS',
        'released': '2023',
        'notes': 'OSS-first alternative to LangSmith; popular self-hosted choice for regulated environments.',
        'websiteUrl': 'https://langfuse.com/',
        'docsUrl': 'https://langfuse.com/docs',
    }),
    ('braintrust', 'Braintrust', {
        'category': 'Observability / eval',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Low',
        'interface': 'Web / SDK',
        'capabilities': 'LLM eval, Trace logging, Playgrounds, Prompt versioning, Dataset management, Online evals',
        'bestFor': 'Teams that want best-in-class eval workflows tied directly to traces and prompts',
        'languages': 'Python, TS',
        'released': '2023',
        'notes': 'Strong UX for offline evals + side-by-side prompt comparisons; favored by AI teams.',
        'websiteUrl': 'https://www.braintrust.dev/',
        'docsUrl': 'https://www.braintrust.dev/docs',
    }),
    ('opentelemetry', 'OpenTelemetry', {
        'category': 'Observability',
        'pricing': 'Free',
        'hosting': 'Self-hosted',
        'openSource': 'Yes',
        'setup': 'Medium',
        'interface': 'SDK / Collector',
        'capabilities': 'Distributed tracing, Metrics, Logs, Vendor-neutral, GenAI semantic conventions',
        'bestFor': 'Vendor-neutral telemetry pipeline you can route to any backend (incl. Langfuse/Datadog)',
        'languages': 'All major',
        'released': '2019',
        'notes': 'Becoming the standard for GenAI traces via the new GenAI semantic conventions.',
        'websiteUrl': 'https://opentelemetry.io/',
        'docsUrl': 'https://opentelemetry.io/docs/',
    }),
    ('argocd', 'Argo CD', {
        'category': 'CI/CD',
        'pricing': 'Free',
        'hosting': 'Self-hosted',
        'openSource': 'Yes',
        'setup': 'Medium',
        'interface': 'Web / CLI',
        'capabilities': 'GitOps, K8s sync, Multi-cluster, App-of-apps, RBAC, Drift detection',
        'bestFor': 'Kubernetes GitOps continuous delivery at scale',
        'languages': 'YAML/Helm/Kustomize',
        'released': '2018',
        'notes': 'CNCF graduated GitOps tool of choice for K8s teams.',
        'websiteUrl': 'https://argo-cd.readthedocs.io/',
        'docsUrl': 'https://argo-cd.readthedocs.io/en/stable/',
    }),
    ('github-actions', 'GitHub Actions', {
        'category': 'CI/CD',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Zero',
        'interface': 'Web / YAML',
        'capabilities': 'Workflows, Matrix builds, Reusable actions, Self-hosted runners, OIDC, Secrets, Environments',
        'bestFor': 'CI/CD tightly integrated with GitHub repos and Copilot/AI-driven workflows',
        'languages': 'All',
        'released': '2019',
        'notes': 'The default CI for GitHub-hosted projects; large marketplace of community Actions.',
        'websiteUrl': 'https://github.com/features/actions',
        'docsUrl': 'https://docs.github.com/en/actions',
    }),
    ('circleci', 'CircleCI', {
        'category': 'CI/CD',
        'pricing': 'Freemium',
        'hosting': 'Both',
        'openSource': 'No',
        'setup': 'Low',
        'interface': 'Web / YAML',
        'capabilities': 'Parallel pipelines, Test splitting, Docker layer caching, Orbs, Insights, OIDC',
        'bestFor': 'High-performance CI with strong test splitting and a mature orb ecosystem',
        'languages': 'All',
        'released': '2011',
        'notes': 'Particularly strong for monorepo pipelines and Docker workloads.',
        'websiteUrl': 'https://circleci.com/',
        'docsUrl': 'https://circleci.com/docs/',
    }),
    ('huggingface-hub', 'Hugging Face Hub', {
        'category': 'Model registry',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Zero',
        'interface': 'Web / CLI / SDK',
        'capabilities': 'Model hosting, Dataset hosting, Spaces, Inference endpoints, Auto-scaling, Private repos',
        'bestFor': 'Hosting, sharing, and serving open-weight LLMs and datasets',
        'languages': 'All',
        'released': '2018',
        'notes': 'Industry-standard registry for open models; many AI agents pull weights directly from HF.',
        'websiteUrl': 'https://huggingface.co/',
        'docsUrl': 'https://huggingface.co/docs',
    }),
    ('ollama', 'Ollama', {
        'category': 'Local LLM runtime',
        'pricing': 'Free',
        'hosting': 'Self-hosted',
        'openSource': 'Yes',
        'setup': 'Zero',
        'interface': 'CLI / API / Desktop',
        'capabilities': 'One-click local LLM, Modelfile, OpenAI-compatible API, GGUF, GPU acceleration, Library of models',
        'bestFor': 'Running open-weight models locally with a Docker-style CLI',
        'languages': 'All (REST API)',
        'released': '2023',
        'notes': 'Easiest way to get a local Llama / Qwen / DeepSeek instance behind an OpenAI-compatible API.',
        'websiteUrl': 'https://ollama.com/',
        'docsUrl': 'https://docs.ollama.com/',
    }),
    ('lm-studio', 'LM Studio', {
        'category': 'Local LLM runtime',
        'pricing': 'Free',
        'hosting': 'Self-hosted',
        'openSource': 'No',
        'setup': 'Zero',
        'interface': 'Desktop GUI / API',
        'capabilities': 'Local LLM GUI, OpenAI-compatible API, GGUF/MLX, Chat UI, Multi-model, RAG',
        'bestFor': 'Non-developers who want a desktop GUI for running local LLMs',
        'languages': 'All (REST API)',
        'released': '2023',
        'notes': 'Polished desktop UI with built-in model browser, chat, and local server.',
        'websiteUrl': 'https://lmstudio.ai/',
        'docsUrl': 'https://lmstudio.ai/docs',
    }),
    ('vllm', 'vLLM', {
        'category': 'Inference server',
        'pricing': 'Free',
        'hosting': 'Self-hosted',
        'openSource': 'Yes',
        'setup': 'Medium',
        'interface': 'CLI / API',
        'capabilities': 'High-throughput inference, PagedAttention, Continuous batching, OpenAI-compatible API, Tensor parallelism',
        'bestFor': 'Production self-hosted inference for open-weight LLMs at scale',
        'languages': 'All (REST API)',
        'released': '2023',
        'notes': 'De facto OSS inference server for open models; powers many private LLM stacks.',
        'websiteUrl': 'https://docs.vllm.ai/',
        'docsUrl': 'https://docs.vllm.ai/en/latest/',
    }),
    ('temporal', 'Temporal', {
        'category': 'Workflow orchestration',
        'pricing': 'Freemium',
        'hosting': 'Both',
        'openSource': 'Yes',
        'setup': 'Medium',
        'interface': 'SDK / CLI / Web',
        'capabilities': 'Durable workflows, Retries, Timers, Event-driven, Multi-language SDKs, Versioning',
        'bestFor': 'Building reliable, long-running AI agent workflows that survive crashes and restarts',
        'languages': 'Go, Java, Python, TS, .NET, PHP',
        'released': '2019',
        'notes': 'Strong fit for agent orchestration; first-class support for long-running async tasks.',
        'websiteUrl': 'https://temporal.io/',
        'docsUrl': 'https://docs.temporal.io/',
    }),
    ('e2b', 'E2B', {
        'category': 'Sandboxed execution',
        'pricing': 'Freemium',
        'hosting': 'Cloud',
        'openSource': 'Yes',
        'setup': 'Low',
        'interface': 'SDK',
        'capabilities': 'Sandboxed VMs, Browser automation, File system, Snapshots, Code interpreter, Long-running tasks',
        'bestFor': 'Running untrusted agent code in isolated cloud sandboxes',
        'languages': 'Python, TS, Go',
        'released': '2023',
        'notes': 'Default sandbox for many code-execution agents and AI app builders.',
        'websiteUrl': 'https://e2b.dev/',
        'docsUrl': 'https://e2b.dev/docs',
    }),
    ('modal', 'Modal', {
        'category': 'Serverless GPU',
        'pricing': 'Pay-per-use',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Low',
        'interface': 'SDK / CLI',
        'capabilities': 'Serverless GPUs, Cron jobs, Web endpoints, Volumes, Containers, Sandboxed agents',
        'bestFor': 'Serverless GPU inference, fine-tuning, and AI agent backends in Python',
        'languages': 'Python',
        'released': '2022',
        'notes': 'Popular choice for hosting model inference and agent backends without managing GPUs.',
        'websiteUrl': 'https://modal.com/',
        'docsUrl': 'https://modal.com/docs',
    }),
    ('runpod', 'RunPod', {
        'category': 'GPU cloud',
        'pricing': 'Pay-per-use',
        'hosting': 'Cloud',
        'openSource': 'No',
        'setup': 'Low',
        'interface': 'Web / CLI / API',
        'capabilities': 'GPU pods, Serverless GPU, Community + Secure cloud, Networked volumes, Templates',
        'bestFor': 'Cheap on-demand GPUs for local LLM inference and fine-tuning',
        'languages': 'All',
        'released': '2022',
        'notes': 'Frequent go-to for low-cost A100/H100 capacity; serverless tier integrates with vLLM/TGI.',
        'websiteUrl': 'https://www.runpod.io/',
        'docsUrl': 'https://docs.runpod.io/',
    }),
]


def insert_all():
    if not os.path.exists(DB):
        raise SystemExit(f'DB not found: {DB}')

    conn = sqlite3.connect(DB)
    cur = conn.cursor()

    layers = {
        'ide': IDE_NEW,
        'llm': LLM_NEW,
        'integration': INTEGRATION_NEW,
        'context': CONTEXT_NEW,
        'agent': AGENT_NEW,
        'others': OTHERS_NEW,
    }

    total_added = 0
    for layer_id, entries in layers.items():
        cur.execute('SELECT COALESCE(MAX(position), -1) FROM options WHERE layer_id=?', (layer_id,))
        next_pos = cur.fetchone()[0] + 1
        added_here = 0
        for opt_id, name, attrs in entries:
            # Skip if already exists
            cur.execute('SELECT 1 FROM options WHERE layer_id=? AND id=?', (layer_id, opt_id))
            if cur.fetchone():
                print(f'  SKIP (exists): {layer_id}/{opt_id}')
                continue
            cur.execute(
                'INSERT INTO options (layer_id, id, name, position) VALUES (?, ?, ?, ?)',
                (layer_id, opt_id, name, next_pos),
            )
            for k, v in attrs.items():
                cur.execute(
                    'INSERT OR REPLACE INTO option_attrs (layer_id, option_id, key, value) VALUES (?, ?, ?, ?)',
                    (layer_id, opt_id, k, v),
                )
            next_pos += 1
            added_here += 1
            total_added += 1
        print(f'{layer_id}: added {added_here} new products')

    conn.commit()
    conn.close()
    print(f'\nTotal new products added: {total_added}')


if __name__ == '__main__':
    insert_all()
