// One-shot script to generate data/flowpicker.db from the legacy LAYERS array.
// Run once: `node tools/build-db.js`. After that, edit flowpicker.db directly
// with DB Browser for SQLite or the sqlite3 CLI — this script is for the
// initial migration only.

const fs = require('fs');
const path = require('path');
const initSqlJs = require('../vendor/sql-wasm.js');

const LAYERS = [
  {
    id: 'ide',
    name: 'IDE / Editor',
    optional: false,
    chipKeys: ['notes'],
    options: [
      {
        id: 'vscode', name: 'VS Code',
        notes: 'Largest extension ecosystem', os: 'macOS, Windows, Linux', pricing: 'Free',
        aiIntegration: 'AI via extension', interface: 'GUI',
        openSource: 'Yes', setup: 'Zero',
        bestFor: 'Extension-rich general development across all languages',
        capabilities: 'Vim mode, Multi-cursor, Remote dev, SSH, WSL, Extensions, Live Share',
        languages: 'All major, via LSP',
        extensibility: 'Extensions',
        collaboration: 'Live Share',
        released: '2015',
        websiteUrl: 'https://code.visualstudio.com/',
        docsUrl: 'https://code.visualstudio.com/docs',
      },
      {
        id: 'cursor', name: 'Cursor',
        notes: 'Best built-in inline AI', os: 'macOS, Windows, Linux', pricing: 'Freemium',
        aiIntegration: 'AI-native', interface: 'GUI',
        openSource: 'No', setup: 'Zero',
        bestFor: 'AI-first development with inline editing and chat',
        capabilities: 'Vim mode, Multi-cursor, AI inline edits, Chat, Agent mode, Tabs, Auto-context',
        languages: 'All major, via LSP',
        extensibility: 'Extensions',
        collaboration: '—',
        released: '2024',
        websiteUrl: 'https://cursor.com/',
        docsUrl: 'https://docs.cursor.com/',
      },
      {
        id: 'zed', name: 'Zed',
        notes: 'Fastest, Rust-native', os: 'macOS, Linux', pricing: 'Free',
        aiIntegration: 'AI-native', interface: 'GUI',
        openSource: 'Yes', setup: 'Zero',
        bestFor: 'Blazing-fast collaborative editing with built-in AI',
        capabilities: 'Vim mode, Multi-cursor, AI inline, CRDT collab, GPU rendering',
        languages: 'All major, via LSP',
        extensibility: 'Extensions',
        collaboration: 'CRDT',
        released: '2023',
        websiteUrl: 'https://zed.dev/',
        docsUrl: 'https://zed.dev/docs',
      },
      {
        id: 'neovim', name: 'Neovim',
        notes: 'Terminal-native, keyboard-first', os: 'macOS, Windows, Linux', pricing: 'Free',
        aiIntegration: 'AI via extension', interface: 'Terminal/TUI',
        openSource: 'Yes', setup: 'Medium',
        bestFor: 'Terminal-native, keyboard-driven editing with deep extensibility',
        capabilities: 'Vim mode, Multi-cursor, Remote dev, Lua scripting, Treesitter, LSP',
        languages: 'All major, via LSP',
        extensibility: 'Extensions',
        collaboration: '—',
        released: '2015',
        websiteUrl: 'https://neovim.io/',
        docsUrl: 'https://neovim.io/doc/',
      },
      {
        id: 'jetbrains', name: 'JetBrains',
        notes: 'Deep language tooling', os: 'macOS, Windows, Linux', pricing: 'Freemium',
        aiIntegration: 'AI via extension', interface: 'GUI',
        openSource: 'No', setup: 'Low',
        bestFor: 'Deep language-aware tooling with refactoring and static analysis',
        capabilities: 'Vim mode, Multi-cursor, Remote dev, Deep refactoring, Profiling, DB tools, Extensions',
        languages: 'Java, Kotlin, Python, JS/TS, C#, Go, many more',
        extensibility: 'Extensions',
        collaboration: 'Code With Me',
        released: '2001',
        websiteUrl: 'https://www.jetbrains.com/',
        docsUrl: 'https://www.jetbrains.com/help/',
      },
      {
        id: 'windsurf', name: 'Windsurf',
        notes: 'AI-native, Cascade agent + Devin cloud agent', os: 'macOS, Windows, Linux',
        pricing: 'Freemium',
        aiIntegration: 'AI-native',
        interface: 'GUI',
        openSource: 'No',
        setup: 'Zero',
        bestFor: 'AI-first development with local + cloud agents and rich MCP ecosystem',
        capabilities: 'Vim mode, AI inline edits, Chat, Cascade agent, Devin cloud agent, Agent Command Center, Web preview, MCP support, Lint fixing, Drag-drop images, Spaces',
        languages: 'All major, via LSP',
        extensibility: 'Extensions',
        collaboration: '—',
        released: '2024',
        websiteUrl: 'https://windsurf.com/',
        docsUrl: 'https://docs.windsurf.com/',
      },
      {
        id: 'fleet', name: 'JetBrains Fleet',
        notes: 'Lightweight, distributed multi-editor', os: 'macOS, Windows, Linux',
        pricing: 'Freemium',
        aiIntegration: 'AI via extension',
        interface: 'GUI',
        openSource: 'No',
        setup: 'Zero',
        bestFor: 'Polyglot distributed development with JetBrains backend intelligence',
        capabilities: 'Vim mode, Multi-cursor, Remote dev, Smart mode, Collaborative editing, Distributed architecture',
        languages: 'All major',
        extensibility: 'Plugins',
        collaboration: 'Code With Me',
        released: '2023',
        websiteUrl: 'https://www.jetbrains.com/fleet/',
        docsUrl: 'https://www.jetbrains.com/help/fleet/',
      },
      {
        id: 'replit', name: 'Replit',
        notes: 'Zero-setup browser IDE with AI Agent', os: 'Browser, macOS, iOS, Android',
        pricing: 'Freemium',
        aiIntegration: 'AI-native',
        interface: 'GUI',
        openSource: 'No',
        setup: 'Zero',
        bestFor: 'Instant prototyping and full-stack development in browser with AI Agent',
        capabilities: 'AI Agent, Deployments, Databases, Object Storage, GitHub import, Secrets manager, Universal package manager, Extensions, Mobile app',
        languages: 'All major, auto-config',
        extensibility: 'Extensions',
        collaboration: 'Multiplayer',
        released: '2016',
        websiteUrl: 'https://replit.com/',
        docsUrl: 'https://docs.replit.com/',
      },
      {
        id: 'visual-studio', name: 'Visual Studio 2022',
        notes: 'Full-featured Microsoft IDE for .NET/C++', os: 'Windows, macOS',
        pricing: 'Freemium',
        aiIntegration: 'AI via extension',
        interface: 'GUI',
        openSource: 'No',
        setup: 'Low',
        bestFor: 'Enterprise .NET, C++, and game development with deep debugging and profiling',
        capabilities: 'Vim mode, Multi-cursor, Deep debugging, Profiling, IntelliCode, Live Share, Test Explorer, NuGet',
        languages: 'C#, C++, VB.NET, F#, .NET ecosystem',
        extensibility: 'Extensions',
        collaboration: 'Live Share',
        released: '2022',
        websiteUrl: 'https://visualstudio.microsoft.com/',
        docsUrl: 'https://learn.microsoft.com/en-us/visualstudio/',
      },
      {
        id: 'sublime-text', name: 'Sublime Text',
        notes: 'Lightweight, blazing-fast GUI editor', os: 'macOS, Windows, Linux',
        pricing: 'Freemium',
        aiIntegration: 'AI via extension',
        interface: 'GUI',
        openSource: 'No',
        setup: 'Zero',
        bestFor: 'Ultra-fast editing with minimal resource usage and deep extensibility',
        capabilities: 'Multi-cursor, Goto Anything, Command palette, Split editing, Snippets, Python plugin API, GPU rendering',
        languages: 'All major, via LSP plugins',
        extensibility: 'Plugins',
        collaboration: '—',
        released: '2008',
        websiteUrl: 'https://www.sublimetext.com/',
        docsUrl: 'https://www.sublimetext.com/docs/',
      },
      {
        id: 'helix', name: 'Helix',
        notes: 'Modern modal editor with built-in LSP', os: 'macOS, Windows, Linux',
        pricing: 'Free',
        aiIntegration: 'AI via extension',
        interface: 'Terminal/TUI',
        openSource: 'Yes',
        setup: 'Low',
        bestFor: 'Batteries-included terminal editing with built-in LSP, Treesitter, and multiple cursors',
        capabilities: 'Vim-like modal editing, Multi-cursor, Built-in LSP, Treesitter, Fuzzy finder, No config needed',
        languages: 'All major, via built-in LSP',
        extensibility: '—',
        collaboration: '—',
        released: '2022',
        websiteUrl: 'https://helix-editor.com/',
        docsUrl: 'https://docs.helix-editor.com/',
      },
      {
        id: 'vim', name: 'Vim',
        notes: 'Modal text editor; legendary efficiency', os: 'macOS, Windows, Linux',
        pricing: 'Free',
        aiIntegration: 'AI via extension',
        interface: 'Terminal/TUI',
        openSource: 'Yes',
        setup: 'High',
        bestFor: 'Terminal-native development, efficiency-focused workflows, Unix/Linux developers',
        capabilities: 'Modal editing, Regex search/replace, Command composability, VimScript plugins, Copilot plugin',
        languages: 'All',
        extensibility: 'Plugins',
        collaboration: '—',
        released: '1991',
        websiteUrl: 'https://www.vim.org/',
        docsUrl: 'https://vimdoc.sourceforge.io/',
      },
      {
        id: 'xcode', name: 'Xcode',
        notes: 'Apple\'s official IDE for Swift/iOS/macOS', os: 'macOS only',
        pricing: 'Free',
        aiIntegration: 'AI via extension',
        interface: 'GUI',
        openSource: 'No',
        setup: 'Low',
        bestFor: 'Apple platform development (iOS, macOS, tvOS, watchOS) and Swift projects',
        capabilities: 'Integrated debugger, Interface Builder, Swift Playgrounds, Performance profiling, Source control',
        languages: 'Swift, Objective-C, C, C++',
        extensibility: 'Extensions',
        collaboration: 'Via Xcode Cloud',
        released: '2003',
        websiteUrl: 'https://developer.apple.com/xcode/',
        docsUrl: 'https://developer.apple.com/documentation/xcode/',
      },
      {
        id: 'android-studio', name: 'Android Studio',
        notes: 'Official IDE for Android/Kotlin development', os: 'macOS, Windows, Linux',
        pricing: 'Free',
        aiIntegration: 'AI via extension',
        interface: 'GUI',
        openSource: 'No',
        setup: 'Low',
        bestFor: 'Android native development, Kotlin/Java projects, emulator-based testing',
        capabilities: 'Android emulator, APK analyzer, Layout Inspector, Built-in debugger, Gradle integration',
        languages: 'Kotlin, Java',
        extensibility: 'Extensions',
        collaboration: 'Via Git',
        released: '2013',
        websiteUrl: 'https://developer.android.com/studio',
        docsUrl: 'https://developer.android.com/studio/intro',
      },
      {
        id: 'emacs', name: 'GNU Emacs',
        notes: 'Infinitely extensible via Elisp scripting', os: 'macOS, Windows, Linux',
        pricing: 'Free',
        aiIntegration: 'AI via extension',
        interface: 'GUI',
        openSource: 'Yes',
        setup: 'High',
        bestFor: 'Highly customizable workflows, power users, Org-mode, terminal-centric development',
        capabilities: 'Multi-file editing, Command execution, Elisp scripting, Thousands of packages, Copilot plugin',
        languages: 'All',
        extensibility: 'Plugins',
        collaboration: '—',
        released: '1985',
        websiteUrl: 'https://www.gnu.org/software/emacs/',
        docsUrl: 'https://www.gnu.org/software/emacs/manual/',
      },
    ],
  },
  {
    id: 'llm',
    name: 'LLM Provider / Model',
    optional: false,
    chipKeys: ['contextWindow'],
    options: [
      {
        id: 'claude-sonnet', name: 'Claude Sonnet 4.6',
        provider: 'Anthropic', hosting: 'Closed/API',
        modelId: 'claude-sonnet-4-6',
        priceTier: 'Mid', priceInput: '$3', priceOutput: '$15', priceCache: '$0.30',
        contextWindow: '200K', contextTier: '128K-500K', maxOutput: '64K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Prompt caching',
        speedTier: 'Standard', latency: 'medium',
        benchmark: 'SWE-bench: high',
        sweBench: '64%', humanEval: '92%', mmlu: '86%',
        bestFor: 'Day-to-day coding, fast agentic loops, balanced cost/quality',
        knowledgeCutoff: 'Apr 2024', released: 'Sep 2025',
        websiteUrl: 'https://www.anthropic.com/claude/sonnet',
        docsUrl: 'https://docs.anthropic.com/en/docs/about-claude/models',
      },
      {
        id: 'claude-opus', name: 'Claude Opus 4.7',
        provider: 'Anthropic', hosting: 'Closed/API',
        modelId: 'claude-opus-4-7',
        priceTier: 'Premium', priceInput: '$15', priceOutput: '$75', priceCache: '$1.50',
        contextWindow: '200K', contextTier: '128K-500K', maxOutput: '32K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Extended thinking, Streaming, Structured output, Prompt caching',
        speedTier: 'Slow/Reasoning', latency: 'medium',
        benchmark: 'SWE-bench: top',
        sweBench: '72%', humanEval: '94%', mmlu: '88%',
        bestFor: 'Complex refactors, agentic coding, hard debugging, deep reasoning',
        knowledgeCutoff: 'Jan 2026', released: 'Nov 2025',
        websiteUrl: 'https://www.anthropic.com/claude/opus',
        docsUrl: 'https://docs.anthropic.com/en/docs/about-claude/models',
      },
      {
        id: 'gpt4o', name: 'GPT-4o',
        provider: 'OpenAI', hosting: 'Closed/API',
        modelId: 'gpt-4o',
        priceTier: 'Mid', priceInput: '$2.50', priceOutput: '$10', priceCache: '$1.25',
        contextWindow: '128K', contextTier: '32K-128K', maxOutput: '16K',
        modality: 'Multimodal (vision + audio)',
        capabilities: 'Vision, Audio, Tool use, Streaming, Structured output',
        speedTier: 'Fast', latency: 'fast',
        benchmark: 'HumanEval: high',
        sweBench: '38%', humanEval: '90%', mmlu: '88%',
        bestFor: 'Multimodal tasks, fast chat, broad general use',
        knowledgeCutoff: 'Oct 2023', released: 'May 2024',
        websiteUrl: 'https://openai.com/index/hello-gpt-4o/',
        docsUrl: 'https://platform.openai.com/docs/models',
      },
      {
        id: 'gemini', name: 'Gemini 2.x',
        provider: 'Google', hosting: 'Closed/API',
        modelId: 'gemini-2.0-pro',
        priceTier: 'Mid', priceInput: '$1.25', priceOutput: '$5', priceCache: '$0.31',
        contextWindow: '1M+', contextTier: '500K+', maxOutput: '8K',
        modality: 'Multimodal (vision + audio)',
        capabilities: 'Vision, Audio, Tool use, Streaming, Structured output, Long context',
        speedTier: 'Fast', latency: 'fast',
        benchmark: 'mid-high',
        sweBench: '52%', humanEval: '86%', mmlu: '85%',
        bestFor: 'Huge documents, video/audio understanding, long-context retrieval',
        knowledgeCutoff: 'Aug 2024', released: 'Dec 2024',
        websiteUrl: 'https://deepmind.google/technologies/gemini/',
        docsUrl: 'https://ai.google.dev/gemini-api/docs/models',
      },
      {
        id: 'llama3', name: 'Llama 3 (Ollama/Groq)',
        provider: 'Meta', hosting: 'Open-weights',
        modelId: 'llama-3.3-70b-instruct',
        priceTier: 'Free', priceInput: 'Free (self-hosted)', priceOutput: 'Free (self-hosted)', priceCache: '—',
        contextWindow: '8K-128K', contextTier: '32K-128K', maxOutput: '8K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, Self-hostable',
        speedTier: 'Fast', latency: 'local-bound',
        benchmark: 'mid',
        sweBench: '28%', humanEval: '81%', mmlu: '82%',
        bestFor: 'Local/offline use, privacy-sensitive work, no-cost experimentation',
        knowledgeCutoff: 'Dec 2023', released: 'Dec 2024',
        websiteUrl: 'https://www.llama.com/',
        docsUrl: 'https://llama.meta.com/docs/',
      },
      {
        id: 'deepseek', name: 'Deepseek',
        provider: 'DeepSeek', hosting: 'Open-weights',
        modelId: 'deepseek-v3',
        priceTier: 'Budget', priceInput: '$0.27', priceOutput: '$1.10', priceCache: '$0.07',
        contextWindow: '128K', contextTier: '32K-128K', maxOutput: '8K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, Self-hostable',
        speedTier: 'Standard', latency: 'medium',
        benchmark: 'high (coding)',
        sweBench: '42%', humanEval: '89%', mmlu: '84%',
        bestFor: 'Cheap high-quality coding, bulk classification, self-host for privacy',
        knowledgeCutoff: 'Jul 2024', released: 'Dec 2024',
        websiteUrl: 'https://www.deepseek.com/',
        docsUrl: 'https://api-docs.deepseek.com/',
      },
      {
        id: 'claude-haiku', name: 'Claude Haiku 4.5',
        provider: 'Anthropic', hosting: 'Closed/API',
        modelId: 'claude-haiku-4-5',
        priceTier: 'Budget', priceInput: '$1', priceOutput: '$5', priceCache: '$0.10',
        contextWindow: '200K', contextTier: '128K-500K', maxOutput: '64K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Prompt caching',
        speedTier: 'Fast', latency: 'fast',
        bestFor: 'High-volume quick tasks, cost-sensitive agentic loops, inline completions',
        knowledgeCutoff: 'Feb 2025', released: 'Oct 2025',
        websiteUrl: 'https://www.anthropic.com/claude/haiku',
        docsUrl: 'https://docs.anthropic.com/en/docs/about-claude/models',
      },
      {
        id: 'deepseek-v4-flash', name: 'DeepSeek V4 Flash',
        provider: 'DeepSeek', hosting: 'Closed/API',
        modelId: 'deepseek-v4-flash',
        priceTier: 'Budget', priceInput: '$0.14', priceOutput: '$0.28', priceCache: '$0.003',
        contextWindow: '1M+', contextTier: '500K+', maxOutput: '384K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, Thinking mode, Prefix completion, FIM',
        speedTier: 'Fast', latency: 'medium',
        benchmark: 'high (coding)',
        sweBench: '48%', humanEval: '92%', mmlu: '86%',
        bestFor: 'Ultra-cheap high-quality coding, bulk classification, context-heavy tasks',
        knowledgeCutoff: 'Jun 2025', released: '2026',
        websiteUrl: 'https://www.deepseek.com/',
        docsUrl: 'https://api-docs.deepseek.com/',
      },
      {
        id: 'deepseek-v4-pro', name: 'DeepSeek V4 Pro',
        provider: 'DeepSeek', hosting: 'Closed/API',
        modelId: 'deepseek-v4-pro',
        priceTier: 'Mid', priceInput: '$0.44', priceOutput: '$0.87', priceCache: '$0.015',
        contextWindow: '1M+', contextTier: '500K+', maxOutput: '384K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, Thinking mode, Deep reasoning',
        speedTier: 'Slow/Reasoning', latency: 'medium',
        benchmark: 'top-tier reasoning',
        sweBench: '62%', humanEval: '95%', mmlu: '88%',
        bestFor: 'Complex reasoning, agentic coding, hard debugging with long context',
        knowledgeCutoff: 'Jun 2025', released: '2026',
        websiteUrl: 'https://www.deepseek.com/',
        docsUrl: 'https://api-docs.deepseek.com/',
      },
      {
        id: 'grok-4.3', name: 'Grok 4.3',
        provider: 'xAI', hosting: 'Closed/API',
        modelId: 'grok-4.3',
        priceTier: 'Budget', priceInput: '$1.25', priceOutput: '$2.50', priceCache: '—',
        contextWindow: '1M+', contextTier: '500K+', maxOutput: '128K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Web search, X search, Code execution',
        speedTier: 'Fast', latency: 'fast',
        bestFor: 'Fast general-purpose coding with native web and X search agent capabilities',
        knowledgeCutoff: 'Nov 2024', released: '2026',
        websiteUrl: 'https://x.ai/',
        docsUrl: 'https://docs.x.ai/',
      },
      {
        id: 'grok-4.20', name: 'Grok 4.20',
        provider: 'xAI', hosting: 'Closed/API',
        modelId: 'grok-4.20-0309-reasoning',
        priceTier: 'Budget', priceInput: '$1.25', priceOutput: '$2.50', priceCache: '—',
        contextWindow: '2M+', contextTier: '500K+', maxOutput: '128K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Reasoning, Web search, X search, MCP',
        speedTier: 'Slow/Reasoning', latency: 'medium',
        bestFor: 'Deep reasoning, multi-step agentic coding, massive context tasks',
        knowledgeCutoff: 'Nov 2024', released: 'Mar 2026',
        websiteUrl: 'https://x.ai/',
        docsUrl: 'https://docs.x.ai/',
      },
      {
        id: 'grok-fast', name: 'Grok 4-1 Fast',
        provider: 'xAI', hosting: 'Closed/API',
        modelId: 'grok-4-1-fast-reasoning',
        priceTier: 'Budget', priceInput: '$0.20', priceOutput: '$0.50', priceCache: '—',
        contextWindow: '2M+', contextTier: '500K+', maxOutput: '128K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Reasoning, MCP',
        speedTier: 'Fast', latency: 'fast',
        bestFor: 'Ultra-cheap fast reasoning for bulk agentic coding and large context retrieval',
        knowledgeCutoff: 'Nov 2024', released: '2025',
        websiteUrl: 'https://x.ai/',
        docsUrl: 'https://docs.x.ai/',
      },
      {
        id: 'mistral-large-3', name: 'Mistral Large 3',
        provider: 'Mistral', hosting: 'Open-weights',
        modelId: 'mistral-large-3',
        priceTier: 'Budget', priceInput: '$0.50', priceOutput: '$1.50', priceCache: '—',
        contextWindow: '256K', contextTier: '128K-500K', maxOutput: '32K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Multilingual, Self-hostable',
        speedTier: 'Standard', latency: 'medium',
        bestFor: 'Top open-weight multipurpose model, multilingual coding, self-hosting with frontier quality',
        knowledgeCutoff: 'May 2025', released: 'Dec 2025',
        websiteUrl: 'https://mistral.ai/',
        docsUrl: 'https://docs.mistral.ai/getting-started/models/',
      },
      {
        id: 'codestral', name: 'Codestral',
        provider: 'Mistral', hosting: 'Closed/API',
        modelId: 'codestral-2508',
        priceTier: 'Budget', priceInput: '$0.20', priceOutput: '$0.60', priceCache: '—',
        contextWindow: '256K', contextTier: '128K-500K', maxOutput: '32K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, FIM, Code completion, Code generation',
        speedTier: 'Fast', latency: 'fast',
        bestFor: 'Specialized code completion and generation, FIM-aware coding, fast IDE completions',
        knowledgeCutoff: 'Jul 2025', released: 'Aug 2025',
        websiteUrl: 'https://mistral.ai/',
        docsUrl: 'https://docs.mistral.ai/getting-started/models/',
      },
      {
        id: 'devstral-2', name: 'Devstral 2',
        provider: 'Mistral', hosting: 'Open-weights',
        modelId: 'devstral-2-123b',
        priceTier: 'Budget', priceInput: '$0.40', priceOutput: '$2.00', priceCache: '—',
        contextWindow: '256K', contextTier: '128K-500K', maxOutput: '32K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, Agentic coding, Multi-step planning, Self-hostable',
        speedTier: 'Standard', latency: 'medium',
        bestFor: 'Open-source coding agent, SWE-bench tasks, complex multi-file refactors',
        knowledgeCutoff: '2025', released: 'Dec 2025',
        websiteUrl: 'https://mistral.ai/',
        docsUrl: 'https://docs.mistral.ai/getting-started/models/',
      },
      {
        id: 'ministral-14b', name: 'Ministral 3 14B',
        provider: 'Mistral', hosting: 'Open-weights',
        modelId: 'ministral-3-14b',
        priceTier: 'Budget', priceInput: '$0.20', priceOutput: '$0.20', priceCache: '—',
        contextWindow: '128K', contextTier: '32K-128K', maxOutput: '16K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Self-hostable, Edge deployable',
        speedTier: 'Fast', latency: 'local-bound',
        bestFor: 'Local coding assistant on laptop, edge deployments, quick completions',
        knowledgeCutoff: '2025', released: 'Dec 2025',
        websiteUrl: 'https://mistral.ai/',
        docsUrl: 'https://docs.mistral.ai/getting-started/models/',
      },
      {
        id: 'mistral-medium-3.5', name: 'Mistral Medium 3.5',
        provider: 'Mistral', hosting: 'Closed/API',
        modelId: 'mistral-medium-3.5',
        priceTier: 'Mid', priceInput: '$2.00', priceOutput: '$8.00', priceCache: '—',
        contextWindow: '256K', contextTier: '128K-500K', maxOutput: '32K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Agentic coding, Reasoning, Multilingual',
        speedTier: 'Standard', latency: 'medium',
        bestFor: 'Frontier-class agentic coding and reasoning at lower cost than Opus/GPT top tiers',
        knowledgeCutoff: '2025', released: '2025',
        websiteUrl: 'https://mistral.ai/',
        docsUrl: 'https://docs.mistral.ai/getting-started/models/',
      },
      {
        id: 'qwen-3', name: 'Qwen 3 (235B)',
        provider: 'Alibaba', hosting: 'Open-weights',
        modelId: 'qwen3-235b-a22b',
        priceTier: 'Free', priceInput: 'Free (self-hosted)', priceOutput: 'Free (self-hosted)', priceCache: '—',
        contextWindow: '128K', contextTier: '32K-128K', maxOutput: '32K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, Thinking mode, MCP, 119 languages, Self-hostable',
        speedTier: 'Slow/Reasoning', latency: 'local-bound',
        benchmark: 'top-tier coding + math',
        sweBench: '53%', humanEval: '94%', mmlu: '88%',
        bestFor: 'Powerful self-hosted reasoning, multilingual coding, agentic workflows with MCP',
        knowledgeCutoff: 'Mar 2025', released: 'Apr 2025',
        websiteUrl: 'https://qwenlm.github.io/blog/qwen3/',
        docsUrl: 'https://qwen.readthedocs.io/',
      },
      {
        id: 'qwen-3.6', name: 'Qwen 3.6',
        provider: 'Alibaba', hosting: 'Open-weights',
        modelId: 'qwen3.6-35b-a3b',
        priceTier: 'Free', priceInput: 'Free (self-hosted)', priceOutput: 'Free (self-hosted)', priceCache: '—',
        contextWindow: '256K', contextTier: '128K-500K', maxOutput: '32K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Thinking mode, Thinking preservation, Agentic coding, Frontend workflows, Self-hostable',
        speedTier: 'Standard', latency: 'local-bound',
        bestFor: 'Agentic coding with sustained multi-turn reasoning, frontend generation, local development',
        knowledgeCutoff: '2026', released: '2026',
        websiteUrl: 'https://ollama.com/library/qwen3.6',
        docsUrl: 'https://qwen.readthedocs.io/',
      },
      {
        id: 'qwen-coder', name: 'Qwen 3 Coder',
        provider: 'Alibaba', hosting: 'Open-weights',
        modelId: 'qwen3-coder-30b',
        priceTier: 'Free', priceInput: 'Free (self-hosted)', priceOutput: 'Free (self-hosted)', priceCache: '—',
        contextWindow: '256K', contextTier: '128K-500K', maxOutput: '32K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, FIM, Code generation, Long context, Self-hostable',
        speedTier: 'Standard', latency: 'local-bound',
        bestFor: 'Open-source coding specialist, long-context code generation, FIM completions on local hardware',
        knowledgeCutoff: '2025', released: '2025',
        websiteUrl: 'https://ollama.com/library/qwen3-coder',
        docsUrl: 'https://qwen.readthedocs.io/',
      },
      {
        id: 'qwen-coder-next', name: 'Qwen 3 Coder Next',
        provider: 'Alibaba', hosting: 'Open-weights',
        modelId: 'qwen3-coder-next',
        priceTier: 'Free', priceInput: 'Free (self-hosted)', priceOutput: 'Free (self-hosted)', priceCache: '—',
        contextWindow: '256K', contextTier: '128K-500K', maxOutput: '32K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, FIM, Agentic coding, Long context, Self-hostable',
        speedTier: 'Standard', latency: 'local-bound',
        bestFor: 'Next-gen open-source coding model optimized for agentic coding and local dev workflows',
        knowledgeCutoff: '2026', released: '2026',
        websiteUrl: 'https://ollama.com/library/qwen3-coder-next',
        docsUrl: 'https://qwen.readthedocs.io/',
      },
      {
        id: 'gemma-4', name: 'Gemma 4 31B',
        provider: 'Google', hosting: 'Open-weights',
        modelId: 'gemma-4-31b',
        priceTier: 'Free', priceInput: 'Free (self-hosted)', priceOutput: 'Free (self-hosted)', priceCache: '—',
        contextWindow: '256K', contextTier: '128K-500K', maxOutput: '32K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Thinking mode, Function calling, Agentic coding, System prompts, Self-hostable',
        speedTier: 'Standard', latency: 'local-bound',
        bestFor: 'Frontier open-weights on workstation, agentic coding, reasoning, local multimodal tasks',
        knowledgeCutoff: '2026', released: '2026',
        websiteUrl: 'https://ollama.com/library/gemma4',
        docsUrl: 'https://ai.google.dev/gemma',
      },
      {
        id: 'gemini-3-flash', name: 'Gemini 3 Flash',
        provider: 'Google', hosting: 'Closed/API',
        modelId: 'gemini-3-flash',
        priceTier: 'Budget', priceInput: '$0.15', priceOutput: '$0.60', priceCache: '—',
        contextWindow: '1M+', contextTier: '500K+', maxOutput: '64K',
        modality: 'Multimodal (vision + audio)',
        capabilities: 'Vision, Audio, Tool use, Streaming, Structured output, Long context, Agentic coding, Near real-time',
        speedTier: 'Fast', latency: 'fast',
        bestFor: 'Fast frontier intelligence, near real-time coding assistance, multimodal agentic loops',
        knowledgeCutoff: '2025', released: '2026',
        websiteUrl: 'https://deepmind.google/technologies/gemini/',
        docsUrl: 'https://ai.google.dev/gemini-api/docs/models',
      },
      {
        id: 'command-r-plus', name: 'Command R+',
        provider: 'Cohere', hosting: 'Closed/API',
        modelId: 'command-r-plus-08-2024',
        priceTier: 'Mid', priceInput: '$2.50', priceOutput: '$10', priceCache: '—',
        contextWindow: '128K', contextTier: '32K-128K', maxOutput: '4K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, RAG-optimized, Multilingual',
        speedTier: 'Standard', latency: 'medium',
        bestFor: 'Enterprise RAG, multilingual coding, document understanding with tool use',
        knowledgeCutoff: 'Aug 2024', released: 'Aug 2024',
        websiteUrl: 'https://cohere.com/pricing',
        docsUrl: 'https://docs.cohere.com/',
      },
      {
        id: 'command-r', name: 'Command R',
        provider: 'Cohere', hosting: 'Closed/API',
        modelId: 'command-r',
        priceTier: 'Budget', priceInput: '$1.00', priceOutput: '$2.00', priceCache: '—',
        contextWindow: '128K', contextTier: '32K-128K', maxOutput: '4K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, RAG-optimized, Multilingual',
        speedTier: 'Fast', latency: 'fast',
        bestFor: 'Cost-effective enterprise RAG, multilingual understanding at budget pricing',
        knowledgeCutoff: 'Mar 2024', released: 'Mar 2024',
        websiteUrl: 'https://cohere.com/pricing',
        docsUrl: 'https://docs.cohere.com/',
      },
      {
        id: 'llama-4', name: 'Llama 4 Maverick',
        provider: 'Meta', hosting: 'Open-weights',
        modelId: 'llama-4-maverick',
        priceTier: 'Free', priceInput: 'Free (self-hosted)', priceOutput: 'Free (self-hosted)', priceCache: '—',
        contextWindow: '1M+', contextTier: '500K+', maxOutput: '16K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Self-hostable, MoE architecture',
        speedTier: 'Fast', latency: 'local-bound',
        bestFor: 'Latest open-weights from Meta, large context, self-hosted coding with vision',
        knowledgeCutoff: '2025', released: '2025',
        websiteUrl: 'https://www.llama.com/',
        docsUrl: 'https://llama.meta.com/docs/',
      },
      {
        id: 'nova-pro', name: 'Amazon Nova Pro',
        provider: 'Amazon', hosting: 'Closed/API',
        modelId: 'amazon-nova-pro',
        priceTier: 'Mid', priceInput: '$0.80', priceOutput: '$3.20', priceCache: '—',
        contextWindow: '300K', contextTier: '128K-500K', maxOutput: '16K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, AWS integration',
        speedTier: 'Standard', latency: 'fast',
        bestFor: 'AWS-integrated coding, enterprise Bedrock deployments, multimodal tasks',
        knowledgeCutoff: '2025', released: '2025',
        websiteUrl: 'https://aws.amazon.com/bedrock/nova/',
        docsUrl: 'https://aws.amazon.com/bedrock/nova/',
      },
      {
        id: 'nova-lite', name: 'Amazon Nova Lite',
        provider: 'Amazon', hosting: 'Closed/API',
        modelId: 'amazon-nova-lite',
        priceTier: 'Budget', priceInput: '$0.06', priceOutput: '$0.24', priceCache: '—',
        contextWindow: '300K', contextTier: '128K-500K', maxOutput: '8K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, AWS integration',
        speedTier: 'Fast', latency: 'fast',
        bestFor: 'Cheapest AWS-native model for high-volume coding tasks, Bedrock deployments',
        knowledgeCutoff: '2025', released: '2025',
        websiteUrl: 'https://aws.amazon.com/bedrock/nova/',
        docsUrl: 'https://aws.amazon.com/bedrock/nova/',
      },
      {
        id: 'nova-micro', name: 'Amazon Nova Micro',
        provider: 'Amazon', hosting: 'Closed/API',
        modelId: 'amazon-nova-micro',
        priceTier: 'Budget', priceInput: '$0.035', priceOutput: '$0.14', priceCache: '—',
        contextWindow: '128K', contextTier: '32K-128K', maxOutput: '8K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, AWS integration',
        speedTier: 'Fast', latency: 'fast',
        bestFor: 'Ultra-low-cost AWS-native for simple coding, routing, high-throughput tasks',
        knowledgeCutoff: '2025', released: '2025',
        websiteUrl: 'https://aws.amazon.com/bedrock/nova/',
        docsUrl: 'https://aws.amazon.com/bedrock/nova/',
      },
      {
        id: 'phi-4', name: 'Phi-4',
        provider: 'Microsoft', hosting: 'Open-weights',
        modelId: 'phi-4',
        priceTier: 'Free', priceInput: 'Free (self-hosted)', priceOutput: 'Free (self-hosted)', priceCache: '—',
        contextWindow: '16K', contextTier: '<32K', maxOutput: '4K',
        modality: 'Text-only',
        capabilities: 'Tool use, Streaming, Structured output, Self-hostable, Small footprint',
        speedTier: 'Fast', latency: 'local-bound',
        bestFor: 'Extremely small self-hosted coding model, edge devices, resource-constrained environments',
        knowledgeCutoff: 'Jun 2024', released: 'Dec 2024',
        websiteUrl: 'https://azure.microsoft.com/en-us/products/phi/',
        docsUrl: 'https://azure.microsoft.com/en-us/products/phi/',
      },
      {
        id: 'openai-o3', name: 'o3',
        provider: 'OpenAI', hosting: 'Closed/API',
        modelId: 'o3',
        priceTier: 'Premium', priceInput: '$10', priceOutput: '$40', priceCache: '$2.50',
        contextWindow: '200K', contextTier: '128K-500K', maxOutput: '100K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Extended thinking, Streaming, Structured output',
        speedTier: 'Slow/Reasoning', latency: 'medium',
        benchmark: 'SWE-bench: top',
        sweBench: '71%', humanEval: '96%', mmlu: '91%',
        bestFor: 'Hardest coding problems, complex multi-step reasoning, advanced debugging',
        knowledgeCutoff: 'Jun 2024', released: 'Apr 2025',
        websiteUrl: 'https://openai.com/o3',
        docsUrl: 'https://platform.openai.com/docs/models',
      },
      {
        id: 'openai-o4-mini', name: 'o4-mini',
        provider: 'OpenAI', hosting: 'Closed/API',
        modelId: 'o4-mini',
        priceTier: 'Budget', priceInput: '$1.10', priceOutput: '$4.40', priceCache: '$0.275',
        contextWindow: '200K', contextTier: '128K-500K', maxOutput: '100K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Reasoning, Streaming, Structured output',
        speedTier: 'Fast', latency: 'fast',
        benchmark: 'strong coding',
        sweBench: '68%', humanEval: '93%', mmlu: '87%',
        bestFor: 'Cheap fast reasoning, agentic coding loops, high-volume tasks',
        knowledgeCutoff: 'Jun 2024', released: 'Apr 2025',
        websiteUrl: 'https://openai.com/o4-mini',
        docsUrl: 'https://platform.openai.com/docs/models',
      },
      {
        id: 'openai-gpt4-1', name: 'GPT-4.1',
        provider: 'OpenAI', hosting: 'Closed/API',
        modelId: 'gpt-4.1',
        priceTier: 'Mid', priceInput: '$2', priceOutput: '$8', priceCache: '$0.50',
        contextWindow: '1M+', contextTier: '500K+', maxOutput: '32K',
        modality: 'Multimodal (vision)',
        capabilities: 'Vision, Tool use, Streaming, Structured output, Long context',
        speedTier: 'Standard', latency: 'fast',
        benchmark: 'high coding',
        sweBench: '55%', humanEval: '92%', mmlu: '88%',
        bestFor: 'Long-context coding, instruction-following, broad general use at mid price',
        knowledgeCutoff: 'Jun 2024', released: 'Apr 2025',
        websiteUrl: 'https://openai.com/',
        docsUrl: 'https://platform.openai.com/docs/models',
      },
      {
        id: 'gemini-2-5-pro', name: 'Gemini 2.5 Pro',
        provider: 'Google', hosting: 'Closed/API',
        modelId: 'gemini-2.5-pro',
        priceTier: 'Premium', priceInput: '$1.25', priceOutput: '$10', priceCache: '—',
        contextWindow: '1M+', contextTier: '500K+', maxOutput: '65K',
        modality: 'Multimodal (vision + audio)',
        capabilities: 'Vision, Audio, Tool use, Extended thinking, Streaming, Structured output, Long context',
        speedTier: 'Standard', latency: 'medium',
        benchmark: 'top-tier',
        sweBench: '63%', humanEval: '92%', mmlu: '90%',
        bestFor: 'Advanced reasoning, multimodal workflows, massive context tasks, agentic coding',
        knowledgeCutoff: 'Jan 2025', released: 'Mar 2025',
        websiteUrl: 'https://deepmind.google/technologies/gemini/',
        docsUrl: 'https://ai.google.dev/gemini-api/docs/models',
      },
      {
        id: 'gemini-2-5-flash', name: 'Gemini 2.5 Flash',
        provider: 'Google', hosting: 'Closed/API',
        modelId: 'gemini-2.5-flash',
        priceTier: 'Budget', priceInput: '$0.30', priceOutput: '$2.50', priceCache: '—',
        contextWindow: '1M+', contextTier: '500K+', maxOutput: '65K',
        modality: 'Multimodal (vision + audio)',
        capabilities: 'Vision, Audio, Tool use, Streaming, Structured output, Long context',
        speedTier: 'Fast', latency: 'fast',
        benchmark: 'strong for speed/cost',
        sweBench: '—', humanEval: '89%', mmlu: '86%',
        bestFor: 'Fast cost-efficient inference with huge context, real-time applications',
        knowledgeCutoff: 'Jan 2025', released: 'May 2025',
        websiteUrl: 'https://deepmind.google/technologies/gemini/',
        docsUrl: 'https://ai.google.dev/gemini-api/docs/models',
      },
    ],
  },
  {
    id: 'integration',
    name: 'Integration Layer',
    optional: false,
    chipKeys: ['compatibility'],
    options: [
      {
        id: 'copilot', name: 'GitHub Copilot',
        compatibility: 'VS Code, JetBrains, Neovim', pricing: 'Paid subscription',
        openSource: 'No', interface: 'In-editor', setup: 'Zero',
        bestFor: 'AI completions and chat across major IDEs from a trusted platform',
        capabilities: 'Inline completion, Chat, Multi-file edits, Agent mode, Code review',
        modelChoice: 'Multiple providers',
        contextHandling: 'Repo-aware',
        privacy: 'Sent to provider',
        released: '2021',
        websiteUrl: 'https://github.com/features/copilot',
        docsUrl: 'https://docs.github.com/en/copilot',
      },
      {
        id: 'continue', name: 'Continue.dev',
        compatibility: 'VS Code, JetBrains', pricing: 'Free',
        openSource: 'Yes', interface: 'In-editor', setup: 'Low',
        bestFor: 'Open-source AI extension with full model and provider flexibility',
        capabilities: 'Inline completion, Chat, Multi-file edits, Agent mode',
        modelChoice: 'BYO model',
        contextHandling: 'Indexed RAG',
        privacy: 'Configurable',
        released: '2023',
        websiteUrl: 'https://continue.dev/',
        docsUrl: 'https://docs.continue.dev/',
      },
      {
        id: 'codeium', name: 'Codeium',
        compatibility: 'VS Code, JetBrains, Vim', pricing: 'Freemium',
        openSource: 'No', interface: 'In-editor', setup: 'Zero',
        bestFor: 'Free AI completions with broad IDE support',
        capabilities: 'Inline completion, Chat, Command palette, Multi-file edits',
        modelChoice: 'Fixed',
        contextHandling: '—',
        privacy: 'Sent to provider',
        released: '2022',
        websiteUrl: 'https://codeium.com/',
        docsUrl: 'https://docs.codeium.com/',
      },
      {
        id: 'cursor-built', name: 'Cursor built-in',
        compatibility: 'Cursor only', pricing: 'Paid subscription',
        openSource: 'No', interface: 'In-editor', setup: 'Zero',
        bestFor: 'Tightest IDE-AI integration with tab-to-apply and inline edits',
        capabilities: 'Inline completion, Chat, Multi-file edits, Agent mode, Tabs, Auto-context, Composer',
        modelChoice: 'Multiple providers',
        contextHandling: 'Indexed RAG',
        privacy: 'Configurable',
        released: '2024',
        websiteUrl: 'https://cursor.com/',
        docsUrl: 'https://docs.cursor.com/',
      },
      {
        id: 'aider', name: 'Aider (terminal)',
        compatibility: 'Any editor (terminal)', pricing: 'BYO API key',
        openSource: 'Yes', interface: 'Terminal/CLI', setup: 'Low',
        bestFor: 'Git-aware AI pair programming from any terminal or editor',
        capabilities: 'Chat, Multi-file edits, Git integration, Map-reduce, Multi-model',
        modelChoice: 'BYO model',
        contextHandling: 'Repo-aware',
        privacy: 'Configurable',
        released: '2023',
        websiteUrl: 'https://aider.chat/',
        docsUrl: 'https://aider.chat/docs/',
      },
      {
        id: 'direct-api', name: 'Direct API / custom',
        compatibility: 'Anywhere you wire it', pricing: 'BYO API key',
        openSource: 'No', interface: 'API/SDK', setup: 'High',
        bestFor: 'Maximum control for bespoke tooling and custom workflows',
        capabilities: '—',
        modelChoice: 'BYO model',
        contextHandling: '—',
        privacy: 'Configurable',
        released: '—',
        websiteUrl: '—',
        docsUrl: '—',
      },
      {
        id: 'cline', name: 'Cline',
        compatibility: 'VS Code, JetBrains, Terminal',
        pricing: 'BYO API key',
        openSource: 'Yes',
        interface: 'In-editor',
        setup: 'Low',
        bestFor: 'Autonomous coding agent in VS Code and terminal with full BYO model flexibility',
        capabilities: 'File edits, Terminal commands, Browser use, Plan/Act modes, MCP, Kanban, CLI, SDK',
        modelChoice: 'BYO model',
        contextHandling: 'Repo-aware',
        privacy: 'Sent to provider',
        released: '2024',
        websiteUrl: 'https://cline.bot/',
        docsUrl: 'https://docs.cline.bot/',
      },
      {
        id: 'windsurf-cascade', name: 'Windsurf Cascade',
        compatibility: 'Windsurf only',
        pricing: 'Freemium',
        openSource: 'No',
        interface: 'In-editor',
        setup: 'Zero',
        bestFor: 'Tightly integrated AI agent with local + cloud agents, MCP, and rich UI',
        capabilities: 'Inline completion, Chat, Multi-file edits, Agent mode, MCP, Lint fixing, Drag-drop images, Web preview, Devin cloud agent, Agent Command Center',
        modelChoice: 'Multiple providers',
        contextHandling: 'Indexed RAG',
        privacy: 'Configurable',
        released: '2024',
        websiteUrl: 'https://windsurf.com/',
        docsUrl: 'https://docs.windsurf.com/',
      },
      {
        id: 'cody', name: 'Sourcegraph Cody',
        compatibility: 'VS Code, JetBrains, Visual Studio, Web',
        pricing: 'Freemium',
        openSource: 'Yes',
        interface: 'In-editor',
        setup: 'Low',
        bestFor: 'Cross-repo AI coding assistant with Sourcegraph code search and context',
        capabilities: 'Chat, Auto-edit, Commands, Prompts, Cross-repo context, Debug, Context filters',
        modelChoice: 'Multiple providers',
        contextHandling: 'Indexed RAG',
        privacy: 'Sent to provider',
        released: '2023',
        websiteUrl: 'https://sourcegraph.com/cody',
        docsUrl: 'https://sourcegraph.com/docs/cody',
      },
      {
        id: 'tabnine', name: 'Tabnine',
        compatibility: 'VS Code, JetBrains, Eclipse, all major IDEs',
        pricing: 'Paid subscription',
        openSource: 'No',
        interface: 'In-editor',
        setup: 'Low',
        bestFor: 'Enterprise-grade AI coding with full privacy controls and self-hosted deployment',
        capabilities: 'Inline completion, Chat, Agentic workflows, CLI agent, Context Engine, MCP, Coaching guidelines, Headless agents',
        modelChoice: 'Multiple providers',
        contextHandling: 'Indexed RAG',
        privacy: 'Configurable',
        released: '2018',
        websiteUrl: 'https://www.tabnine.com/',
        docsUrl: 'https://docs.tabnine.com/',
      },
      {
        id: 'openhands', name: 'OpenHands',
        compatibility: 'Any editor (web UI)',
        pricing: 'BYO API key',
        openSource: 'Yes',
        interface: 'In-editor',
        setup: 'Low',
        bestFor: 'Open-source autonomous AI software engineer accessible via browser or CLI',
        capabilities: 'Chat, Multi-file edits, Terminal commands, Browser, Git, Multi-agent, Sandboxed',
        modelChoice: 'BYO model',
        contextHandling: 'Repo-aware',
        privacy: 'Configurable',
        released: '2024',
        websiteUrl: 'https://www.openhands.dev/',
        docsUrl: 'https://docs.openhands.dev/',
      },
      {
        id: 'codex-cli', name: 'OpenAI Codex CLI',
        compatibility: 'Any editor (terminal)',
        pricing: 'BYO API key',
        openSource: 'Yes',
        interface: 'Terminal/CLI',
        setup: 'Low',
        bestFor: 'Official OpenAI CLI coding agent with sandboxed execution and multi-model support',
        capabilities: 'Chat, Multi-file edits, Terminal commands, Sandboxed execution, Git integration, Multi-model',
        modelChoice: 'BYO model',
        contextHandling: 'Repo-aware',
        privacy: 'Sent to provider',
        released: '2025',
        websiteUrl: 'https://github.com/openai/codex',
        docsUrl: 'https://github.com/openai/codex',
      },
      {
        id: 'amazon-q', name: 'Amazon Q Developer',
        compatibility: 'VS Code, JetBrains, AWS Console',
        pricing: 'Freemium',
        openSource: 'No',
        interface: 'In-editor',
        setup: 'Low',
        bestFor: 'AWS-heavy projects, enterprise teams on Bedrock, architectural guidance',
        capabilities: 'Inline completion, Chat, Multi-file edits, Agent mode, AWS best practices, Security scanning',
        modelChoice: 'Fixed',
        contextHandling: 'Indexed RAG',
        privacy: 'Sent to provider',
        released: '2024',
        websiteUrl: 'https://aws.amazon.com/q/developer/',
        docsUrl: 'https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/what-is.html',
      },
      {
        id: 'jetbrains-ai', name: 'JetBrains AI Assistant',
        compatibility: 'All JetBrains IDEs',
        pricing: 'Freemium',
        openSource: 'No',
        interface: 'In-editor',
        setup: 'Zero',
        bestFor: 'JetBrains ecosystem users wanting native AI with zero config and local model option',
        capabilities: 'Inline completion, Chat, Multi-file edits, Test generation, Code explanation, /web command, Local model support',
        modelChoice: 'Multiple providers',
        contextHandling: 'Indexed RAG',
        privacy: 'Configurable',
        released: '2023',
        websiteUrl: 'https://www.jetbrains.com/ai/',
        docsUrl: 'https://www.jetbrains.com/help/ai-assistant/',
      },
      {
        id: 'qodo', name: 'Qodo',
        compatibility: 'VS Code, GitHub PR, CLI',
        pricing: 'Freemium',
        openSource: 'Yes',
        interface: 'In-editor',
        setup: 'Low',
        bestFor: 'AI-powered code review, automated test generation, PR quality gates',
        capabilities: 'Multi-agent PR review, Bug detection, Security analysis, Unit test generation, Code suggestions',
        modelChoice: 'BYO model',
        contextHandling: 'Repo-aware',
        privacy: 'Configurable',
        released: '2022',
        websiteUrl: 'https://www.qodo.ai/',
        docsUrl: 'https://docs.qodo.ai/',
      },
      {
        id: 'supermaven', name: 'Supermaven',
        compatibility: 'VS Code, JetBrains, Neovim, Zed',
        pricing: 'Freemium',
        openSource: 'No',
        interface: 'In-editor',
        setup: 'Zero',
        bestFor: 'Context-rich code completion with <100ms latency and 300K–1M token context window',
        capabilities: 'Inline completion, Chat, Large context window (300K free / 1M Pro), Coding style adaptation',
        modelChoice: 'Fixed',
        contextHandling: 'Repo-aware',
        privacy: 'Sent to provider',
        released: '2024',
        websiteUrl: 'https://supermaven.com/',
        docsUrl: 'https://supermaven.com/docs',
      },
    ],
  },
  {
    id: 'context',
    name: 'Context / RAG Layer',
    optional: false,
    chipKeys: ['hosting', 'staleness'],
    options: [
      {
        id: 'none', name: 'None (vanilla)',
        indexLimit: '—', hosting: '—', staleness: 'N/A',
        setup: 'Zero', openSource: 'N/A',
        bestFor: 'Simple projects where the LLM context window is sufficient',
        capabilities: 'None',
        indexType: 'None',
        updateMode: '—',
        privacy: '—',
        released: '—',
        websiteUrl: '—',
        docsUrl: '—',
      },
      {
        id: 'cursor-cb', name: '@codebase (Cursor)',
        indexLimit: 'Large', hosting: 'Cloud', staleness: 'auto',
        setup: 'Zero', openSource: 'No',
        bestFor: 'Zero-config semantic search across a codebase inside Cursor',
        capabilities: 'Semantic search, Symbol search, File-level relevance',
        indexType: 'Embeddings',
        updateMode: 'Real-time',
        privacy: 'Cloud index',
        released: '2024',
        websiteUrl: 'https://cursor.com/',
        docsUrl: 'https://docs.cursor.com/',
      },
      {
        id: 'continue-idx', name: 'Continue codebase indexing',
        indexLimit: 'Repo-size', hosting: 'Local', staleness: 'manual',
        setup: 'Low', openSource: 'Yes',
        bestFor: 'Local-first codebase indexing for use with any model',
        capabilities: 'Embedding search, Symbol search, Multi-provider',
        indexType: 'Embeddings',
        updateMode: 'On-demand',
        privacy: 'Local-only',
        released: '2023',
        websiteUrl: 'https://continue.dev/',
        docsUrl: 'https://docs.continue.dev/',
      },
      {
        id: 'greptile', name: 'Greptile',
        indexLimit: 'Large', hosting: 'Cloud', staleness: 'auto',
        setup: 'Low', openSource: 'No',
        bestFor: 'Cloud-hosted codebase indexing with semantic and code-aware search',
        capabilities: 'Semantic search, Symbol search, Code-aware search, API',
        indexType: 'AST / Hybrid',
        updateMode: 'Real-time',
        privacy: 'Cloud index',
        released: '2023',
        websiteUrl: 'https://greptile.com/',
        docsUrl: 'https://docs.greptile.com/',
      },
      {
        id: 'chromadb', name: 'Local ChromaDB',
        indexLimit: 'You manage', hosting: 'Local', staleness: 'manual',
        setup: 'High', openSource: 'Yes',
        bestFor: 'DIY local embedding-based codebase search with full control',
        capabilities: 'Embedding-based search, Vector storage, API',
        indexType: 'Embeddings',
        updateMode: 'On-demand',
        privacy: 'Local-only',
        released: '2023',
        websiteUrl: 'https://www.trychroma.com/',
        docsUrl: 'https://docs.trychroma.com/',
      },
      {
        id: 'sourcegraph-cody', name: 'Sourcegraph Cody Context',
        indexLimit: 'Large',
        hosting: 'Cloud',
        staleness: 'auto',
        setup: 'Low',
        openSource: 'Yes',
        bestFor: 'Cross-repo code search and context for large organizations with Sourcegraph backend',
        capabilities: 'Semantic search, Symbol search, Cross-repo, Code intelligence, AST-based',
        indexType: 'AST / Hybrid',
        updateMode: 'Real-time',
        privacy: 'Cloud index',
        released: '2023',
        websiteUrl: 'https://sourcegraph.com/cody',
        docsUrl: 'https://sourcegraph.com/docs/cody',
      },
      {
        id: 'copilot-idx', name: 'GitHub Copilot codebase indexing',
        indexLimit: 'Large',
        hosting: 'Cloud',
        staleness: 'auto',
        setup: 'Zero',
        openSource: 'No',
        bestFor: 'Zero-config repo indexing natively integrated with GitHub Copilot chat and completions',
        capabilities: 'Semantic search, Symbol search, Repo-wide context, GitHub integration',
        indexType: 'Embeddings',
        updateMode: 'Real-time',
        privacy: 'Cloud index',
        released: '2024',
        websiteUrl: 'https://github.com/features/copilot',
        docsUrl: 'https://docs.github.com/en/copilot',
      },
      {
        id: 'pinecone', name: 'Pinecone',
        indexLimit: 'Large',
        hosting: 'Cloud',
        staleness: 'manual',
        setup: 'Medium',
        openSource: 'No',
        bestFor: 'Managed vector database for production-scale RAG and semantic code search',
        capabilities: 'Embedding-based search, Vector storage, API, Serverless, Namespaces, Metadata filtering',
        indexType: 'Embeddings',
        updateMode: 'On-demand',
        privacy: 'Cloud index',
        released: '2021',
        websiteUrl: 'https://www.pinecone.io/',
        docsUrl: 'https://docs.pinecone.io/',
      },
      {
        id: 'qdrant', name: 'Qdrant',
        indexLimit: 'Large',
        hosting: 'Cloud',
        staleness: 'manual',
        setup: 'Medium',
        openSource: 'Yes',
        bestFor: 'Open-source vector DB with self-hosted and cloud options for codebase RAG',
        capabilities: 'Embedding-based search, Vector storage, API, Quantization, Filtering, Multi-tenant',
        indexType: 'Embeddings',
        updateMode: 'On-demand',
        privacy: 'Configurable',
        released: '2021',
        websiteUrl: 'https://qdrant.tech/',
        docsUrl: 'https://qdrant.tech/documentation/',
      },
      {
        id: 'weaviate', name: 'Weaviate',
        indexLimit: 'Large',
        hosting: 'Cloud',
        staleness: 'manual',
        setup: 'Medium',
        openSource: 'Yes',
        bestFor: 'Hybrid vector + keyword search with built-in vectorization for codebase RAG',
        capabilities: 'Hybrid search, Embedding-based search, Vector storage, API, Native vectorizer, Multi-modal',
        indexType: 'AST / Hybrid',
        updateMode: 'On-demand',
        privacy: 'Configurable',
        released: '2019',
        websiteUrl: 'https://weaviate.io/',
        docsUrl: 'https://weaviate.io/developers/weaviate',
      },
      {
        id: 'lancedb', name: 'LanceDB',
        indexLimit: 'You manage',
        hosting: 'Local',
        staleness: 'manual',
        setup: 'Medium',
        openSource: 'Yes',
        bestFor: 'Serverless embedded vector DB, zero-setup local codebase RAG for desktop apps',
        capabilities: 'Embedding-based search, Vector storage, API, Embedded, Serverless, Lance columnar format',
        indexType: 'Embeddings',
        updateMode: 'On-demand',
        privacy: 'Local-only',
        released: '2023',
        websiteUrl: 'https://lancedb.com/',
        docsUrl: 'https://lancedb.github.io/lancedb/',
      },
      {
        id: 'windsurf-idx', name: 'Windsurf codebase indexing',
        indexLimit: 'Large',
        hosting: 'Cloud',
        staleness: 'auto',
        setup: 'Zero',
        openSource: 'No',
        bestFor: 'Zero-config codebase indexing natively integrated with Windsurf Cascade agent',
        capabilities: 'Semantic search, Symbol search, File-level relevance, Cascade integration',
        indexType: 'Embeddings',
        updateMode: 'Real-time',
        privacy: 'Cloud index',
        released: '2024',
        websiteUrl: 'https://windsurf.com/',
        docsUrl: 'https://docs.windsurf.com/',
      },
      {
        id: 'pgvector', name: 'pgvector',
        indexLimit: 'You manage',
        hosting: 'Local',
        staleness: 'manual',
        setup: 'Low',
        openSource: 'Yes',
        bestFor: 'Vector search inside an existing PostgreSQL database; no new infra required',
        capabilities: 'Vector similarity search, HNSW indexing, L2/cosine/inner product distance, Hybrid search',
        indexType: 'HNSW',
        updateMode: 'On-demand',
        privacy: 'Local-only',
        released: '2021',
        websiteUrl: 'https://github.com/pgvector/pgvector',
        docsUrl: 'https://github.com/pgvector/pgvector',
      },
      {
        id: 'milvus', name: 'Milvus',
        indexLimit: 'Large',
        hosting: 'Cloud',
        staleness: 'auto',
        setup: 'Medium',
        openSource: 'Yes',
        bestFor: 'Billion-scale vector indexing for production RAG; self-hosted or Zilliz Cloud managed',
        capabilities: 'HNSW/IVF/DiskANN indexing, Hybrid search, Scalar filtering, GPU acceleration, Streaming inserts',
        indexType: 'HNSW',
        updateMode: 'Real-time',
        privacy: 'Configurable',
        released: '2019',
        websiteUrl: 'https://milvus.io/',
        docsUrl: 'https://milvus.io/docs',
      },
      {
        id: 'redis-vector', name: 'Redis Vector Search',
        indexLimit: 'Large',
        hosting: 'Cloud',
        staleness: 'auto',
        setup: 'Low',
        openSource: 'Yes',
        bestFor: 'Sub-millisecond vector search for real-time RAG; ideal for teams already on Redis',
        capabilities: 'High-speed similarity search, Hybrid search, JSON + bitmap filtering, Exact match + vector',
        indexType: 'HNSW',
        updateMode: 'Real-time',
        privacy: 'Configurable',
        released: '2023',
        websiteUrl: 'https://redis.io/solutions/redis-vector-database/',
        docsUrl: 'https://redis.io/docs/latest/develop/interact/search-and-query/search/vector-search/',
      },
      {
        id: 'mem0', name: 'Mem0',
        indexLimit: 'You manage',
        hosting: 'Cloud',
        staleness: 'auto',
        setup: 'Low',
        openSource: 'Yes',
        bestFor: 'Long-term agent memory and multi-session context continuity across conversations',
        capabilities: 'Structured memory management, Semantic search, Auto compression, Chat history, Pluggable vector DB backend',
        indexType: 'Embeddings',
        updateMode: 'Real-time',
        privacy: 'Configurable',
        released: '2024',
        websiteUrl: 'https://mem0.ai/',
        docsUrl: 'https://docs.mem0.ai/',
      },
    ],
  },
  {
    id: 'agent',
    name: 'Agent / Orchestration Layer',
    optional: true,
    chipKeys: ['notes'],
    options: [
      {
        id: 'none', name: 'None',
        notes: 'Autocomplete / chat only', autonomy: 'None',
        interface: 'N/A', openSource: 'N/A', cost: 'N/A', setup: 'Zero',
        bestFor: 'Projects that only need inline completions and chat',
        capabilities: 'None',
        modelChoice: '—',
        guardrails: '—',
        released: '—',
        websiteUrl: '—',
        docsUrl: '—',
      },
      {
        id: 'aider-arch', name: 'Aider (architect)',
        notes: 'Plan-then-edit loop', autonomy: 'Assist',
        interface: 'Terminal/CLI', openSource: 'Yes', cost: 'BYO API key', setup: 'Low',
        bestFor: 'Plan-then-edit workflow with git safety net for complex changes',
        capabilities: 'Tool use, Multi-step planning, Git integration, Shell access, Multi-model',
        modelChoice: 'BYO model',
        guardrails: 'Approval gates',
        released: '2023',
        websiteUrl: 'https://aider.chat/',
        docsUrl: 'https://aider.chat/docs/',
      },
      {
        id: 'swe-agent', name: 'SWE-agent',
        notes: 'Issue-resolution agent', autonomy: 'Autonomous',
        interface: 'Terminal/CLI', openSource: 'Yes', cost: 'BYO API key', setup: 'Medium',
        bestFor: 'Autonomous issue resolution and PR generation from GitHub issues',
        capabilities: 'Tool use, Multi-step planning, Shell access, Browser, Git, File editing',
        modelChoice: 'BYO model',
        guardrails: 'Sandboxed',
        released: '2024',
        websiteUrl: 'https://swe-agent.com/',
        docsUrl: 'https://swe-agent.com/latest/',
      },
      {
        id: 'claude-code', name: 'Claude Code',
        notes: 'CLI agent, full repo access', autonomy: 'Semi-autonomous',
        interface: 'Terminal/CLI', openSource: 'No', cost: 'Paid subscription', setup: 'Zero',
        bestFor: 'Anthropic CLI agent with full repo awareness and terminal access',
        capabilities: 'Tool use, Multi-step planning, Shell access, Browser, MCP, Git, File editing',
        modelChoice: 'Fixed',
        guardrails: 'Approval gates',
        released: '2025',
        websiteUrl: 'https://www.anthropic.com/claude-code',
        docsUrl: 'https://docs.anthropic.com/en/docs/claude-code',
      },
      {
        id: 'langgraph', name: 'Custom LangGraph',
        notes: 'DIY pipelines', autonomy: 'Autonomous',
        interface: 'Framework/SDK', openSource: 'Yes', cost: 'BYO API key', setup: 'High',
        bestFor: 'Build custom multi-agent workflows with full control and state management',
        capabilities: 'Tool use, Multi-step planning, State graphs, Custom tools, Human-in-the-loop, Multi-agent',
        modelChoice: 'BYO model',
        guardrails: '—',
        released: '2024',
        websiteUrl: 'https://www.langchain.com/langgraph',
        docsUrl: 'https://langchain-ai.github.io/langgraph/',
      },
      {
        id: 'cline-agent', name: 'Cline Agent',
        notes: 'Autonomous VS Code/CLI coding agent, BYO model', autonomy: 'Autonomous',
        interface: 'In-editor',
        openSource: 'Yes', cost: 'BYO API key', setup: 'Low',
        bestFor: 'Fully autonomous agentic coding in VS Code with Plan/Act modes and MCP',
        capabilities: 'Tool use, Multi-step planning, Shell access, Browser, MCP, Git, File editing, Kanban, CLI, SDK',
        modelChoice: 'BYO model',
        guardrails: 'Approval gates',
        released: '2024',
        websiteUrl: 'https://cline.bot/',
        docsUrl: 'https://docs.cline.bot/',
      },
      {
        id: 'devin', name: 'Devin',
        notes: 'End-to-end autonomous SWE agent with cloud sandbox', autonomy: 'Autonomous',
        interface: 'In-editor',
        openSource: 'No', cost: 'Paid subscription', setup: 'Zero',
        bestFor: 'Hands-off task completion with a managed cloud agent that works asynchronously',
        capabilities: 'Tool use, Multi-step planning, Browser, Shell, Long-running tasks, PR generation, Sandboxed execution',
        modelChoice: 'Fixed',
        guardrails: 'Sandboxed',
        released: '2024',
        websiteUrl: 'https://devin.ai/',
        docsUrl: 'https://docs.devin.ai/',
      },
      {
        id: 'windsurf-cascade-agent', name: 'Windsurf Cascade Agent',
        notes: 'Local + cloud dual-agent system (Cascade + Devin)', autonomy: 'Semi-autonomous',
        interface: 'In-editor',
        openSource: 'No', cost: 'Freemium', setup: 'Zero',
        bestFor: 'Hybrid local and cloud agents with unified command center and MCP ecosystem',
        capabilities: 'Tool use, Multi-step planning, Shell access, MCP, Git, File editing, Lint fixing, Web preview, Agent Command Center, Drag-drop images',
        modelChoice: 'Multiple providers',
        guardrails: 'Approval gates',
        released: '2024',
        websiteUrl: 'https://windsurf.com/',
        docsUrl: 'https://docs.windsurf.com/',
      },
      {
        id: 'openhands-agent', name: 'OpenHands Agent',
        notes: 'Open-source autonomous AI software engineer', autonomy: 'Autonomous',
        interface: 'In-editor',
        openSource: 'Yes', cost: 'BYO API key', setup: 'Low',
        bestFor: 'Open-source autonomous coding agent with sandboxed execution and multi-agent support',
        capabilities: 'Tool use, Multi-step planning, Browser, Shell, Git, File editing, Multi-agent, Sandboxed',
        modelChoice: 'BYO model',
        guardrails: 'Sandboxed',
        released: '2024',
        websiteUrl: 'https://www.openhands.dev/',
        docsUrl: 'https://docs.openhands.dev/',
      },
      {
        id: 'codex-cli-agent', name: 'OpenAI Codex CLI Agent',
        notes: 'Official OpenAI terminal agent with sandboxed execution', autonomy: 'Semi-autonomous',
        interface: 'Terminal/CLI',
        openSource: 'Yes', cost: 'BYO API key', setup: 'Low',
        bestFor: 'Official OpenAI CLI agent for sandboxed coding tasks with multi-model support',
        capabilities: 'Tool use, Multi-step planning, Shell access, Sandboxed execution, Git, File editing, Multi-model',
        modelChoice: 'BYO model',
        guardrails: 'Sandboxed',
        released: '2025',
        websiteUrl: 'https://github.com/openai/codex',
        docsUrl: 'https://github.com/openai/codex',
      },
      {
        id: 'cody-agent', name: 'Sourcegraph Cody Agent',
        notes: 'AI coding agent with cross-repo context awareness', autonomy: 'Assist',
        interface: 'In-editor',
        openSource: 'Yes', cost: 'Freemium', setup: 'Low',
        bestFor: 'Cross-repo AI coding assistance with Sourcegraph-powered context awareness',
        capabilities: 'Tool use, Multi-step planning, Auto-edit, Commands, Cross-repo context, Debug',
        modelChoice: 'Multiple providers',
        guardrails: 'Approval gates',
        released: '2023',
        websiteUrl: 'https://sourcegraph.com/cody',
        docsUrl: 'https://sourcegraph.com/docs/cody',
      },
      {
        id: 'tabnine-agent', name: 'Tabnine Agent',
        notes: 'Enterprise AI agent with context engine and coaching', autonomy: 'Semi-autonomous',
        interface: 'In-editor',
        openSource: 'No', cost: 'Paid subscription', setup: 'Low',
        bestFor: 'Enterprise agentic coding with organizational context, coaching, and full privacy controls',
        capabilities: 'Tool use, Multi-step planning, MCP, Git, CLI agent, Context Engine, Coaching guidelines, Headless agents',
        modelChoice: 'Multiple providers',
        guardrails: 'Approval gates',
        released: '2025',
        websiteUrl: 'https://www.tabnine.com/',
        docsUrl: 'https://docs.tabnine.com/',
      },
      {
        id: 'autogen', name: 'AutoGen',
        notes: 'Microsoft multi-agent conversation framework', autonomy: 'Semi-autonomous',
        interface: 'Framework/SDK',
        openSource: 'Yes', cost: 'BYO API key', setup: 'Low',
        bestFor: 'Multi-agent conversations, complex research workflows, human-in-the-loop automation',
        capabilities: 'Tool use, Multi-agent communication, Human-in-the-loop, Function calling, Async execution',
        modelChoice: 'BYO model',
        guardrails: 'Approval gates',
        released: '2023',
        websiteUrl: 'https://microsoft.github.io/autogen/',
        docsUrl: 'https://microsoft.github.io/autogen/docs/Getting-Started/',
      },
      {
        id: 'crewai', name: 'CrewAI',
        notes: 'Role-based agent teams, pip install', autonomy: 'Semi-autonomous',
        interface: 'Framework/SDK',
        openSource: 'Yes', cost: 'BYO API key', setup: 'Low',
        bestFor: 'Team-based workflows, content creation pipelines, hierarchical task execution',
        capabilities: 'Tool use, Role assignment, Task orchestration, Memory integration, Async execution',
        modelChoice: 'BYO model',
        guardrails: 'Approval gates',
        released: '2023',
        websiteUrl: 'https://crewai.com/',
        docsUrl: 'https://docs.crewai.com/',
      },
      {
        id: 'pydantic-ai', name: 'Pydantic AI',
        notes: 'Type-safe agents with structured output validation', autonomy: 'Assist',
        interface: 'Framework/SDK',
        openSource: 'Yes', cost: 'BYO API key', setup: 'Low',
        bestFor: 'Production agents that need validated structured outputs and type-safe tool calls',
        capabilities: 'Tool use, Type hints, Structured responses, Async support, Streaming, Result validation',
        modelChoice: 'BYO model',
        guardrails: 'Approval gates',
        released: '2024',
        websiteUrl: 'https://ai.pydantic.dev/',
        docsUrl: 'https://ai.pydantic.dev/agents/',
      },
      {
        id: 'smolagents', name: 'Smolagents',
        notes: 'Hugging Face lightweight code-execution agent', autonomy: 'Semi-autonomous',
        interface: 'Framework/SDK',
        openSource: 'Yes', cost: 'BYO API key', setup: 'Low',
        bestFor: 'Code-generation-first agents, Hugging Face model ecosystem, research use cases',
        capabilities: 'Tool use, Python code execution, HF model integration, Flexible action space, Sandboxed code runner',
        modelChoice: 'BYO model',
        guardrails: 'Sandboxed',
        released: '2024',
        websiteUrl: 'https://huggingface.co/docs/smolagents/',
        docsUrl: 'https://huggingface.co/docs/smolagents/',
      },
    ],
  },
];

(async () => {
  const wasmBinary = fs.readFileSync(path.join(__dirname, '..', 'vendor', 'sql-wasm.wasm'));
  const SQL = await initSqlJs({ wasmBinary });
  const db = new SQL.Database();

  db.run(`
    CREATE TABLE layers (
      id        TEXT PRIMARY KEY,
      name      TEXT NOT NULL,
      optional  INTEGER NOT NULL DEFAULT 0,
      position  INTEGER NOT NULL
    );

    CREATE TABLE layer_chip_keys (
      layer_id  TEXT NOT NULL REFERENCES layers(id),
      key       TEXT NOT NULL,
      position  INTEGER NOT NULL,
      PRIMARY KEY (layer_id, key)
    );

    CREATE TABLE options (
      layer_id  TEXT NOT NULL REFERENCES layers(id),
      id        TEXT NOT NULL,
      name      TEXT NOT NULL,
      position  INTEGER NOT NULL,
      PRIMARY KEY (layer_id, id)
    );

    CREATE TABLE option_attrs (
      layer_id   TEXT NOT NULL,
      option_id  TEXT NOT NULL,
      key        TEXT NOT NULL,
      value      TEXT,
      PRIMARY KEY (layer_id, option_id, key),
      FOREIGN KEY (layer_id, option_id) REFERENCES options(layer_id, id)
    );

    CREATE INDEX idx_options_layer ON options(layer_id, position);
    CREATE INDEX idx_option_attrs_option ON option_attrs(layer_id, option_id);
  `);

  const insLayer = db.prepare('INSERT INTO layers (id, name, optional, position) VALUES (?, ?, ?, ?)');
  const insChip  = db.prepare('INSERT INTO layer_chip_keys (layer_id, key, position) VALUES (?, ?, ?)');
  const insOpt   = db.prepare('INSERT INTO options (layer_id, id, name, position) VALUES (?, ?, ?, ?)');
  const insAttr  = db.prepare('INSERT INTO option_attrs (layer_id, option_id, key, value) VALUES (?, ?, ?, ?)');

  LAYERS.forEach((layer, layerPos) => {
    insLayer.run([layer.id, layer.name, layer.optional ? 1 : 0, layerPos]);
    (layer.chipKeys || []).forEach((key, i) => insChip.run([layer.id, key, i]));
    layer.options.forEach((opt, optPos) => {
      insOpt.run([layer.id, opt.id, opt.name, optPos]);
      for (const [key, value] of Object.entries(opt)) {
        if (key === 'id' || key === 'name') continue;
        insAttr.run([layer.id, opt.id, key, value == null ? null : String(value)]);
      }
    });
  });

  insLayer.free(); insChip.free(); insOpt.free(); insAttr.free();

  const bytes = db.export();
  const outPath = path.join(__dirname, '..', 'data', 'flowpicker.db');
  fs.writeFileSync(outPath, Buffer.from(bytes));
  console.log(`Wrote ${outPath} (${bytes.length} bytes)`);
  db.close();
})().catch(err => {
  console.error(err);
  process.exit(1);
});
